HardBoiledSmith/johanna

- run_describe_vpc.py
- describe_rds_security_groups
- vpc-id가 None일 경우 임의의 정상 테스트용 파라메터를 넣었습니다.
- describe_eb_security_groups
- vpc-id가 None일 경우 임의의 정상 테스트용 파라메터를 넣었습니다.
<https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html>
언제부터 바뀐지에 대한 정보는 찾지 못하였고, 파라메터 검사에 대한 여부에 대한 정보는 없었습니다.
테스트를 해본 결과 Security_groups 조회하는 cli 명령어가 파라메터를 검사하게끔 변한 것 같습니다.
vpc-id 에대서 파라메터를 'vpc- ' 로 시작해야 올바른 파라메터로 인식하고 돌려주게 패치된 것 같습니다.
> GEN-5206 describe exception 해결

- aws_iam/aws-sns-sms-log-policy.json
- aws_iam/aws-sns-sms-log-role.json
- run_create_cloudwatch_dashboard.py
- run_terminate_cloudwatch_dashboard.py
- sms 전송 갯수 표시 위젯을 추가함
- terminate 시킬시 log 에 등록 하지 않도록 하지만 Delivery statistics 는 꺼지지 않는다. 물리적으로 끌 수 있는 기능은 없어 보임
- `./run_create_cloudwatch_dashboard.py` 를 하면, magi 를 매번 받아와서, `cloudwatch/__global___ap-northeast-2.json` 파일이 계속 master 에서 가져오는데, 아래 코드를 주석 치고 https://github.com/HardBoiledSmith/magi/pull/462 에 `cloudwatch/__global___ap-northeast-2.json` 
에서 받아 magi 를 직접 수정 해주면 편하다.
- https://github.com/HardBoiledSmith/johanna/blob/b7ff82fc5bf05ed41d3e59188cb22b4f742f59cf/run_create_cloudwatch_dashboard.py#L323
- us-east-1 리전으로 변경 하고 SNS > Text messaging (SMS) > Publish text message 로 메시지를 보내 준다
- johanna 로 `./run_create_cloudwatch_dashboard.py __global__` 실행하면 아래와 같이 나오는는데, `SNS: send sms` 생기면 성공이다.
- `./run_terminate_cloudwatch_dashboard.py -f` 하면, 위젯들은 다 사리지고,  SNS > Text messaging (SMS) …
> GEN-5764 add sms widget

- run_create_cloudwatch_alarm.py
- run_terminate_cloudwatch_alarm.py
- lambda 들에 대해서 Error count Cloudwatch 모니터링 강화
- dashbord 의 경우는 아래 코드로 인해 자동으로 생성됨
- error count 로 하려고 했으나 alarm용 widget 이여서, 성공 여부를 보여주는 차트나을 것 같아 따로 작업 하지 않음
https://github.com/HardBoiledSmith/johanna/blob/master/run_create_cloudwatch_dashboard.py#L273-L311
- `run_create_lambda.py <name>` 으로 lambda 를 생성
- config.json 에 `cloudwatch.ALARMS` 에 아래 같은 설정을 추가함
```
{
"AWS_DEFAULT_REGION": <region>,
"COMPARISON_OPERATOR": "LessThanThreshold",
"DATAPOINTS_TO_ALARM": "1",
"DESCRIPTION": "Success of <name> (<region>) is less than 100 in 5min", 
"EVALUATION_PERIODS": "1",
"NAME": <name>,
"SNS_TOPIC_NAME": "cloudwatch-alarm",
"THRESHOLD": "100.0",
"TYPE": "lambda"
}
```
- `run_create_cloudwatch_alarm.py <name>` 으로 alarm 를 생성
- `run_create_cloudwatch_dashboard.py <alarm name>` 으로 alarm widget 를 생성
> GEN-5528 Add cloudwatch alarm for lambda error

- run_create_eb_windows.py
- Elasticbeanstalk python, windows 버전 최신으로 업데이트
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
python은 최신 버전이 `64bit Amazon Linux 2018.03 v2.9.2 running Python 3.6`으로 이미 최신 버전이어서 수정할 것이 없었습니다.
- 제가 아직 johanna 및 aws_cli에 미숙하여 따로 테스트를 진행해보지 못했습니다.. pr close 한 후 테스트 이후 다시 열겠습니다.
> GEN-6146 update windows version

- run_create_ses.py
- run_create_sns.py
- run_terminate_sns.py
- 이메일 렌더링에 에러 발생시 SNS 에서 이메일 받아 보는 기능 추가
- https://docs.aws.amazon.com/ko_kr/ses/latest/DeveloperGuide/send-personalized-email-api.html
- boto3 로 create_template 로 템플릿을 올리고, send_templated_email 를 통해 메일을 보낼때 템플릿에 parameter 를 빼면 렌더링 에러 발생
- 등록한 메일로 메일 오면 성공
```
"sns": [
{
"AWS_DEFAULT_REGION": "us-east-1",
"NAME": "fail-ses",
"TYPE": "topic",
"EMAIL": "<email>"
}
],
"ses": {
"CONFIGURATION_SETS": [
{
"NAME": "randering-fail",
"EVENT_DESTINATIONS" : [
{
"ENABLED": true,
"MATCHING_TYPE": ["renderingFailure"],
"NAME": "RanderingFail",
"TYPE" : "sns",
"SNS_TOPICS_NAME": "us-east-1/fail-ses"
}
]
}
]
}
```
> GEN-6157 Add Configuration Sets sns Destination

- run_create_codebuild_github.py
- run_terminate_codebuild.py
- codebuild 시 parameter store 를 사용 하는 경우 같은 리전의 parameter store 에 접글 하도록 rule 세팅
- 서울이 아닌 다른 리전에서 parameter store 값을 세팅하고 codebuild 생성후 실행
> GEN-6416 fix access parameter default region

- aws_iam/aws-appstream-role.json
- run_create_appstream.py
- run_terminate_appstream.py
- appstream의 image builder, stack을 cli 커멘드로 사용하기 위해서는 필수로 2가지 role을 필요로함. 따라서 해당 role을 추가 및 삭제하는 코드를 추가작업.
1. AWS CLI에서 어떻게 해야 iam을 생성할 수 있는지에 대해서 몰라 여기저기 삽으로 찔러봤습니다.
[ https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-service.html ] 문서에 잘 나와있었는데 나중에 삽질하다가 찾게 됐습니다. ㅠㅠ
2. AWS CLI 에서 role을 생성하기까지 성공을 했는데 builder, stack 생성 시 role을 찾을 수 없다하여 왜 그런지 policy를 GUI로 만들때와 CLI로 만들었을 때 차이를 비교해 보니 iamge builder, stack 및 fleet을 생성할 때 해당 (**AmazonAppStreamServiceAccess**)  Role이 필요한대 , 이 Role은 GUI로 생성할 시 path를 /service-role/ 로 자동 생성해주고 있었습니다. CLI로 생성할 경우는 path 옵션에 service-role로 지정을 해줘야합니다.
3. 처음 이슈 GEN-7697에서 요구했던 사항 중 iam은 총 3개였습니다.
- AmazonAppStreamServiceAccess
- ApplicationAutoScalingForAmazonAppStreamAccess
- AWSServiceRoleForApplicationAutoScaling_AppStreamFleet
첫 번째, 두 번째는 생성이 …
> GEN-7697 appstream iam 생성 및 삭제

- run_create_appstream.py
- `AWSServiceRoleForApplicationAutoScaling_AppStreamFleet` 의 권한 없이 scale 가능해 따로 role 작업을 하지 않고 scale 가능을 추가 했습니다.
- config.json 에 appstream 의 naoko-stack 에 `DESIRED_INSTANCES` 옵션을 추가 하고 원하는 값을 넣어 
Maximum capacity 가 해당 값으로 할당 되는지 확인
> GEN-7979 Add scale option in appstream

- buildspec.yml
- Codebuild amazon linux2 에서 돌아갈수 있도록 수정
- build_test_johanna 의 image 를 aws/codebuild/amazonlinux2-x86_64-standard:2.0 로 변경
> GEN-8329 Fix run for amazon linux2

- run_create_appstream_builder.py
- run_create_appstream_stack_fleet.py
- run_terminate_appstream_builder.py
- run_terminate_appstream_stack_fleet.py
기존에 만들어진 image가 없는 상태에서 run_create_appstream 하면 builder 생성후 stack/fleet을 바로 생성하지 못해 죽음
1의 상황때문에 이미지를 build 해놓고 다시 run_create_appstream 하면 이미 builder가 만들어져있는 상태라 exception 발생
2의 상황 때문에 builder 생성 로직을 주석처리해서 무시해도 fleet/stack에서 에러가 발생하여 생성이 안됨
제안: builder 생성과 stack/fleet 생성을 서로다른 run_* 로 분리할 필요 있음 (run_create_appstream_builder.py, run_create_appstream_stack_fleet.py)
1.  johanna에서 ./run_create_appstream_builder.py 를 실행 하여 이미지 빌더가 뜨면 이미지를 생성해 주세요
2. 이미지 생성이 완료되면 ./run_create_appstream_stack_fleet.py을 실행해 주세요
3. 테스트 이후에는 생성한 terminate 시켜주시기 바랍니다
> GEN-8254 run_create_appstream builder, stack&fleet 코드 분리

- run_create_cloudwatch_alarm.py
- SMS 실패및 전송 개수에 대한 Alarm을 추가하기 위한 함수 추가
- magi로부터 새롭게 config파일 생성
- `./run_create_cloudwatch_alarm.py sns_failed`
`magi`
https://github.com/HardBoiledSmith/magi/pull/516
> GEN-7241 Add cloudwatch alarm function for sns

- run_create_appstream_stack_fleet.py
- web에서 modal창을 사용함으로 인해 redirct_url 옵션이 필요없어져 제거하였습니다.
- stack및 fleet이 뜬 후에 redirect url 설정이 들어가 있는지 확인해야 합니다.
confing.json에서 STACK 의 파라미터 중 REDIRECT_URL 값을 지워야합니다.
> GEN-8512 appstream embed stack redirct url 제거

- README.md
- run_create_cloudfront.py
- run_create_route53.py
- run_terminate_cloudfront.py
- run_terminate_route53.py
- cloudfront(cdn)과 route53(dns) 생성하고 삭제 할 수 있는 스크립트 추가
- config.json 파일에 access key 와 scret key 를 의존 하고 나머지 설정을 args 로 받아 처리
- 삭제시에는 dv 가 포함 되지 않은 도메인은 실행 되지 않도록 작성
- test web 를 위한 cloud front 와 route53 설정을 진행하면 좋음
- `./run_create_cloudfront.py -b <s3 bucket name> -e <s3 bucket end point> -a <acm-arn> -c <cname> -f` 로 생성
- 예 : `./run_create_cloudfront.py -b hyeonku-dv-test.hbsmith.io -e hyeonku-dv-test.hbsmith.io.s3-website.ap-northeast-2.amazonaws.com -a arn:aws:acm:us-east-1:...:certificate/... -c hyeonku-dv-test.hbsmith.io -f`
- `./run_create_route53.py -ah Z2FDTNDATAQYW2 -at cloudfront -d <cloudfront domain name> -hn hbsmith.io -n <domain> -r A -f` 로 생성
- 예 : `./run_create_route53.py -ah Z2FDTNDATAQYW2 -at cloudfront -d hyeonku-dv-test.hbsmith.io -hn hbsmith.io -n …
> GEN-7085 Add cloudfront and route53

- run_create_appstream_fleet_autoscale.py
- run_terminate_appstream_fleet_autoscale.py
-https://docs.aws.amazon.com/appstream2/latest/developerguide/autoscaling.html
기존 5번의 autoscale 정책을 사용하던 방식에서 1번(용량기반 scale out) 과 3번(용량이반 scale in) 정책으로 변경
- Appstream을 fleet을 생성 후 해당 autoscale 파일을 실행시켜 주세요.
> DEV-8908 appstream auto Scale

- run_describe_cloudwatch.py
- run_describe_vpc.py
- `ec2 describe-vpc-peering-connections` 명령어에서 에러 발생시 empty string 값이 와서 에러 처리를 해줌
- cloudwatch metric 에서 `METRIC_NAME` 값이 없는 녀석도 있어서, 없을 경어 empty string 기본 값을 설정
- `run.py describe` 실행시 실패 없이 진행 되면 성공
> DEV-9329 describe_vpc_peering_connection 에러 발생시, false 반환하도록 설정

- run_create_acm_certificate.py
- run_terminate_acm_certificate.py
- acm 인증서 수동으로 생성 했던 것을 자동화 함
- 이메일로 인증시 제상님께 이야기 필요함
- 아래 설정을  `config.json` 추가 해서 acm certificate 생성 삭제 진행
- 이메일로 인증시 제상님께 이야기 필요함(생성시만)
```
"acm": [
{
"NAME": "hbsmith.io",
"DOMAIN_NAME" : "hbsmith.io",
"ADDITIONAL_NAMES": [
"*.hbsmith.io"
],
"VALIDATION_METHOD": "EMAIL"
}
]
```
> DEV-9320 acm certificate 생성 삭제 하는 스크립트 추가

- run_create_lambda_cron.py
- lambda 생성시 concurrency 를 조절 할 수 있도록 수정
- 예약된 동시성 구성 관련 내용 : https://docs.aws.amazon.com/ko_kr/lambda/latest/dg/configuration-concurrency.html#configuration-concurrency-reserved
- config.json 에서 lambda 에서 CONCURRENCY 옵션을 추가로 주고, 생성된 lambda 에 Concurrency > Reserve concurrency 에 해당 값이 반영 되었는지 확인
> DEV-9336 lambda 생성시 concurrency 를 조절 할 수 있도록 수정

- run_create_s3_bucket.py
- run_terminate_s3_bucket.py
- 외부에 공개된 result 버켓에 CORS 설정이 없어 DV 환경에서 Deep QA 실행 결과를 못봄 (브라우저에서 CORS 문제로 막힘)
- s3 주소를 사용중인 dv 환경의 경우 `웹호스팅`을 켜는 버킷에 대해 CORS 설정을 추가 필요
- config.json에 `WEB_HOSTING`을 활용
- ./run_create_s3.py [email id]-dv-hbsmith-result 실행 
- `./run_create_s3.py jaypae95-dv-hbsmith-result
- 사진과 같이 CORS 설정이 다 되어있는 지 확인
- ./run_terminate_s3.py [email id]-dv-hbsmith-result 실행 
- `./run_terminate_s3.py jaypae95-dv-hbsmith-result
- 새로고침 하여 사진과 같이 CORS 설정이 잘 지워졌는 지 확인
> DEV-9649 Add S3 CORS

- run_create_eb_windows.py
eb gendo 프로비저닝 시 파일 구조로 인해 lamda의 경로가 변경됨.
gendo artifact를 이전에 사용하던 구조와 동일하게 조정
> DEV-10352 Gendo eb에 올릴 때 gendo-artifact.zip을 이전과 같은 구조로 되도록 수정.

- run.py
- rds 세팅 하면 바로 reset datebase 할 수 없어 긴시간을 wait 해야 하는데 `run_create_ec2_client_vpn` 를 `run_create_rds` 뒤에 배치 해서 대기 시간이 없음
https://github.com/HardBoiledSmith/johanna/blob/a96dc00127be9312cb83204e68e487bbfc344d6a/run_codebuild_wait_done.py#L96
- `run.py create` 를 실행 해서 문제 없으면 성공
- codebuild project 생성후 wait 가 없이 바로 실행 됨
> DEV-10154 run.py create 빌드 시간을 줄기이 위해 동작 순서 변경

- run_create_vpc.py
- aws cli1 에서 동작을 위해 aws cli2 를 위해 추가한 base64 무시 하는 설정을 주석 처리함
> DEV-10553 comment ignore base64

- run_create_cloudwatch_dashboard.py
- gendo autoscale 모니터링을 위해 , HealthyHostCount, UnHealthyHostCount, ApproximateNumberOfMessagesVisible 지표를 동시해 표현 하면 파악이 용의 해서 여러 metric 이 한 chart 에 보여질 필요가 있음
- 기존에 metric 1번째만 사용 해서 여러 metrics 기진 cloudwatch 설정이 있나 확인 해 보았으나 모두 단일한 metric 만 있어 로직 변동으로 기존 기능에 영향을 없을 것으로 판단됨
- beanstalk 를  세팅 하고 `run_create_cloudwatch_dashboard.py <beanstalk name>` 으로 dashboard 만들고 정상적으로 나오는지 확인
> DEV-10652 cloudwatch chart 에서 여러 metric 이 한 chart 에 보여지도록 수정

- README.md
- run_create_eb.py
- run_create_eb_django_al2.py
- run_create_lambda_ses_sqs.py
- 기존 Amazon Linux 1 플랫폼을 사용하던 django application 을 Amazon Linux 2 에 디플로이할 수 있습니다.
- `.platform`
- Amazon Linux 2 플랫폼에 추가된 기능입니다.
- [nerv] elastic beanstalk(gunicorn)에서 사용되는 nginx 설정 파일은 `./platform`에, vagrant(uwsgi)환경에서 사용되는 nginx 설정 파일은 `configuration` 안에 저장되어 있습니다. 
- [nerv] 사용 안되는 파일/코드 삭제.
- [nerv] Procfile 처리
- gunicorn 은 ini 파일을 통해 실행하려면, pastedeploy 라는 패키지를 추가 설치해야 합니다. (`pip install pastedeploy`)
- 그러므로 필요한 설정값은 Procfile 에 명시하는 것으로 마무리했습니다.
- https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/1315602496/Elastic+Beanstalk+AL2
- https://github.com/HardBoiledSmith/johanna/pull/414
- https://github.com/HardBoiledSmith/nerv/pull/282
- https://github.com/HardBoiledSmith/magi/pull/683
- eb 에 종속적인 인프라를 모두 프로비전합니다.
- config 파일의 nerv 항목의 TYPE 을 아래와 같이 "django_amazon_linux2"로 변경합니다.
```json …
```
> DEV-10708 django 어플리케이션을 Elastic Beanstalk 의 Python & Amazon Linux 2 플랫폼에 디플로이할 수 있는 기능 추가

- run_create_cloudwatch_alarm.py
- run_create_cloudwatch_dashboard.py
- gendo 대시보드의 sqs 지표 대상이 잘못 표기가 되어 있어 수정 해야함.
- vagrant johanna를 띄운 후 run_common파일에서 reset_template_dir 함수의 git clone 브랜치를 해당 브랜치로 받도록 변경해주세요.
- ./run_create_cloudwatch_dashboard.py gendo 커멘드를 통해 환경을 띄워주세요.
config.json으로 세팅한 aws 계정으로 접속해 cloudwatch 대시보드탭 -> __gendo_ap-northeast-2  을 들어가 아래 스크린샷의 탭을 확인해주세요.
본 이미지는 dv환경 풀 인프라를 띄워서 체크 된 데이터들 입니다.
연관 PR
https://github.com/HardBoiledSmith/magi/pull/707
> DEV-10869 Cloudwatch Gendo Dashboard SQS 지표 수정

- run_create_cloudwatch_alarm.py
- GendoActiveStatus에 alarm 추가
- Metric = SuccessCount 가 1시간동안 0이면 알람 발생 
- GendoActiveStatus를 gendo_ap-northeast-2 대시보드에 추가
- AWS gendo를 테스트 하기 위한 환경을 구성해 주세요. ( iam, vpc, rds, client_vpn, sachiel, sqs, lambda, gendo, cloudwatchbash board , cloudwatch alarm )
johanna를 통해 환경을 구성할 때 cloudwatch 및 gendo를 생성할 때 DEV-8941 브랜치로 올라가게끔 작업을 해야합니다.
- 구성이 완료 되면 구성한 app console로 접속하여 테스트를 실행시켜 Gendo가 실행 후 결과를 기록하도록 합니다.
- cloudwatch Dashbard에 gendo_ap-northeast-2 탭에 들어가 GendoActiveStatus의 지표(IdleCount, BucyCount, SuccessCount)가 기록되어야 합니다.
- 지표에 따른 알람이 잘 동작해야 합니다.
**1시간동안 6번 체크하여 SuccessCount 지표의 Sum이 1이상일 아닐 경우 정상**
**1시간동안 6번 체크하여 SuccessCount 지표의 Sum이 1미만일 아닐 경우 알람**
gendo_ap-northeast-2대시보드에 GendoActiveStatus 지표가 추가된 Dashboard 
관련 PR
https://github.com/HardBoiledSmith/gendo/pull/490 …
> DEV-8941 gendo 난죽택 관련 metric 수정 - 오동작 또는 미동작시 알람처리

- run_export_client_vpn_ovpn.py
- [aws 공식문서](https://docs.aws.amazon.com/ko_kr/cli/latest/userguide/cliv2-migration.html#cliv2-migration-binaryparam)에 명시되어있는 문제입니다.
- `--cli-binary-format raw-in-base64-out` 옵션 추가.
- 추후 스토리 포인트를 더 할당하여 본 이슈에서 수정한 라인을 제거하고  json 만드는 과정을 정리해야 할 것 같습니다.
- vagrant johanna 프로비저닝이 정상적으로 됩니다.
- run_export_client_vpn_ovpn.py 명령 시 아래 스크린샷과 같이 메일이 정상적으로 도착하여야 합니다.
> DEV-10649 run_export_client_vpn_ovpn.py 메일이 깨지는 현상 수정

- run_create_eb_windows.py
- gendo 를 띄울 때 Enhanced Monitoring 을 활성화 함
- 각 인스턴스의 상태를 확인 할 수 있음
- johanna 로 iam, vpc, eb(gendo) 를 띄운뒤 Enhanced Monitoring 을 활성화 됐는지 확인
- gendo Health 가 Ok(Green 이 아닌) 보이는지 확인
> DEV-10781 gendo 를 띄울 때 Enhanced Monitoring 을 활성화 함

- run_create_iam.py
- run_terminate_iam.py
- EC2 콘솔 > 연결 > Session Manager : 웹 UI 로 콘솔 접근이 가능하도록 IAM Policy 추가.
- 관련 문서 : https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/1575453109/SSM+For+Elastic+Beanstalk
- AWS System Manager > Session Manager > 기본 설정 > “Linux 인스턴스에 대해 Run As 지원 활성화” 를 통해 ssm-user 를 ec2-user 등으로 변경할 수 있습니다.
- 키페어 제거 작업은 추후 진행 여부를 결정하기로 스크럼 회의 때 결정되었습니다.
- johanna 가 정상적으로 프로비저닝되어야 합니다.
- iam > vpc > rds 순으로 프로비저닝 후 eb 를 프로비저닝하였을 때 ec2 콘솔에서 스크린샷과 같이 기능 접근이 가능해야 합니다.
https://user-images.githubusercontent.com/29401441/105632829-9c954400-5e98-11eb-88f3-09f0b49229ca.mov
> DEV-11090 SSM 을 위한 IAM policy 추가.

- run_common.py
- run_create_eb_django.py
- run_create_eb_django_al2.py
- run_create_eb_windows.py
- AWS VPC AZ 2 -> 4개로 확장.
- 확장 된 인프라에 맞게 eb(nerv, sachiel, gendo)가 생성 되도록 설정 변경.
- gendo의 경우 old_environment가 교체될 때 old env의 cloud watch alarm 제거 되도록 변경.
- https://github.com/HardBoiledSmith/magi/pull/720 의 config 값이 세팅되어 있어야 합니다.
- daily_cd를 위해 20분간 슬립을 거는 방식을 사용하도록 하겠습니다.
- ./run.py iam, vpc를 실행해 주세요.
- AWS Console로 접속하여 vpc 세팅들을 체크해 주세요. Subnet, routeTable, DB subnet group들이 설정이 되어 있어야 합니다.
관련 문서는 https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/1569751074/ap-northeast-2b+ap-northeast-2d+OP 에 있습니다.
- VPC 생성이 되었다면 ./run.py create_rds, ./run_create_ec2_client_vpn.py 후 DB를 세팅해주세요.
- rds 세팅이 끝나면 EB를 생성해 주세요. 
- 이 외 추가적으로 테스트해보기 위해서는 나머지 인프라 자원을 띄워주세요.
- 생성한 인프라들을 보면서 에러가 있는지 체크해주세요.
- vpc eb에 생성 된 자원들은 rds로 접속이 가능해야 합니다.
- Gendo의 경우 오래된 자원 교체되는 과정을 보기 위해서 ./run_create_eb.py gendo 를 해주어야 …
> DEV-11097 HBsmith AZ 4개로 확장 및 Desired Capacity 조절.

- aws_iam/aws-elasticbeanstalk-ec2-policy.json
- elasticbeanstalk 의 django 코드에서 aws credentials 를 삭제하는 것에 대응하여 ec2 인스턴스에서 SQS로 접근할 수 있도록 권한을 추가하였습니다.
- 관련 인프라를 본 브랜치로 프로비저닝하여 성공하여야 합니다.
- 일부러 nerv에 에러를 발생하여 sqs를 통하여 이메일을 전송받을 수 있어야 합니다.
> DEV-11282 nerv의 eb-ec2 에서 sqs 접근을 위한 policy 추가

- run_create_iam.py
- run_terminate_iam.py
- AWS Elastic Beanstalk Managed Policy Deprecation 이메일을 기준으로 4/15 이후부터 deprecated되는 policy(AWSElasticBeanstalkService)를 새 policy (AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy)로 변경
- AWSElasticBeanstalkService 를 AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy로 변경
- OP 계정의 경우 AWSElasticBeanstalkManagedUpdatesCustomerRolePolicy를 먼저 붙이고 AWSElasticBeanstalkService를 제거필요
- DEV-11414로 EB 환경을 띄웠을때 에러가 없는지 확인
> DEV-11414: change AWSElasticBeanstalkService to newer policy

- run_create_eb_django.py
- run_create_eb_django_al2.py
- run_terminate_eb.py
- run_terminate_eb_old_environment.py
httpd, nginx exception 등은 알람 메일로 수집이 안되기 때문에 cloudwatch log에 알람 설정 추가 필요 
참고 사이트 : https://theithollow.com/2017/12/11/use-amazon-cloudwatch-logs-metric-filters-send-alerts/
- sachiel, nerv 서버에 대한 처리 필요
- /aws/elasticbeanstalk/nerv-*/var/log/nginx/error.log
- /aws/elasticbeanstalk/sachiel-*/var/log/httpd/error_log
관련 PR
https://github.com/HardBoiledSmith/magi/pull/749
- 위 관련 PR magi DEV-11312에서 config.json을 생성해 주세요.
- johhanna에서 ./run.py create_iam, vpc, rds를 띄어주세요.
- /run_create_ec2_client_vpn.py를 실행 후 ovpn을 발급받아주세요.
- 발급완료 후 rds에 데이터를 넣어주세요.
- ./run.py create_sqs , create_sns를 실행해 주세요.
- 해당 브랜치의 ./run_create_eb.py sachiel과 ./run_create_eb.py nerv를 실행해 주세요.
- ./run_create_lambda.py cloudwatch_send_alarm 을 실행 해 주세요.
app console에 접속하여 cloudwatch 서비스로 접속 해주세요.
- …
> DEV-11312 cloudwatch alarm에 sachiel, nerv에서 발생하는 예외로그에 대한 알람 추가

- run_create_eb_windows.py
- https://hbsmith.atlassian.net/browse/DEV-11712 문제는 gendo.exe.config 의존에 따라 생기는 걸로 파악중
- gendo 바이너리 빌드시 gendo.exe.config내에 아래와 같이 어셈블리 버전 정보가 자동으로 포함이 되는데 johanna에서 이 부분이 제거된 파일로 강제로 덮어 씌워버리고, 이에 의해 잘못된 버전을 레퍼런스 하는 문제가 발생되는걸로 추정됨
```
<runtime>
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
<dependentAssembly>
<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
<bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
</dependentAssembly>
</assemblyBinding>
```
- johanna 에서 gendo.exe.config를 덮어씌우는 코드를 제거하여 문제를 해결시도함
> DEV-11712 gendo.exe.config 의존성 제거

- run_create_eb_windows.py
- DEV-10281 에서 누락된 gendo 쪽에 EnhancedHealthAuthEnabled 옵션 추가하는 작업 수행
- https://hbsmith.atlassian.net/browse/DEV-10281
- 5/31일 이전에 배포 필수
- 본 PR을 적용해도 gendo 프로비저닝에 문제가 없어야 합니다.
> DEV-11960: Add EnhancedHealthAuthEnabled

- run_create_lambda_sqs.py
- sachiel_batch_result 람다의 제한시간이 2분(120초)으로 설정되어 있눈대 종종 이를 넘겨서 에러가 발생하는 문제 해소 (스샷참고)
- 이 경우 timeout 이 발생했다는 로그가 남고 lambda가 종료되어 버림
- 2분을 두배인 4로 업그레이드 (120초 -> 240초)
- 위 PR 배포후 cloudwatch 그래프가 240초 미만으로 실행됨을 확인
> DEV-12423 increase timeout 120 -> 240

- run_create_eb_django.py
- run_create_eb_windows.py
- EBS 볼륨 타입으로 gp2 대비 20% 정도의 비용절감 효과가 있는 GP3 도입 (https://ahmedahamid.com/which-is-better/)
- 참고: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalinglaunchconfiguration
- DEV-12492로 EB 인스턴스 생성후 Root Volume 타입이 GP3로 변경되었음을 확인
> DEV-12492 set root volume for EB instance as GP3

- run_common.py
- https://aws.amazon.com/premiumsupport/knowledge-center/switch-acm-certificate/ 에 의거하여 ACM 인증서의 인증 방식을 email에서 DNS로 변경
- Route53에 관련 DNS 레코드는 8/10에 추가완료
- https://github.com/HardBoiledSmith/magi/pull/797 와 연관이슈
- https://hbsmith.atlassian.net/browse/DEV-12341 OP 패치 이후 본 hack 제거
- OP EB 패치시 ARN 끝자리가 224로 끝나는 acm 인증서 (DNS 인증)을 정상적으로 이용 가능한지 확인
> DEV-12525 Change ACM validation method (email -> DNS)

- run_create_route53_health_check.py
- run_create_sns.py
- run_terminate_route53_health_check.py
[AS-IS]
- AWS 자원 중 landing page, hbsmith web, sachiel, gedno에 대해 모니터링을 하기 위한 작업.
[TO-BE]
- 공개 망에 노출된 자원은 route53 health check 서비스를 통해 주기적으로 요청을 보내 이상이 생겼을 시 알림을 줌.
- Gendo같은 private자원은 별도의 cloud watch의 데이터 기준으로 이상을 체크.
알림의 순서는 cloudwatch -> sns -> pagerduty -> statuspage
- 개인 세팅은 AWS 자원까지만 해당하며, Pageduty, Statuspage는 별도의 QA, DV를 위해 개설된 것은 없습니다. 따라서, PAGERDUTY키는 따로 설정하지 않고 작성하도록 하겠습니다.
- 해당 브랜치의 johanna, magi의 config 파일을 풀어주세요.
- magi에 각 개인별 -variable파일에 아래의 값을 추가해 주어야 합니다.
```
"PAGEDUTYAPPKEY_HBSMITH_WEB": "",
"PAGEDUTYAPPKEY_GENDO": "",
"PAGEDUTYAPPKEY_LANDING_PAGE": "",
"PAGEDUTYAPPKEY_SACHIEL": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_SACHIEL": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_HBSMITH_WEB": "",
"ROUTE53_HEALTH_CHECK_TARGET_DOMAIN_LANDING_PAGE": ""
``` 
- …
> DEV-12944 AWS 모니터링 툴 + Pager Duty 연동

- run_create_eb_django.py
- .git 경로에 대한 공격시도를 nginx 측에서 차단하기 위해 rule을 추가하였으나 해당 rule이 발생시키는 정보로그에 의해 PagerDuty alarm 발생
- 공격 방어가 성공적으로 이루어졌기 때문에 해당 로그를 metric filter에서 제외
- AWS 환경에서 테스트
- sachiel, nerv 둘중 하나를 프로비저닝
- sachiel, nerv에 대해서 `GET /.git/gitconfig` 등으로 조회시도
- 402 access denied 가 응답으로 오는지 확인
- Cloudwatch 또는 PD에서 관련 알람이 떨어지지 않음
> DEV-13555 sachiel-*_nginx_error_log: .git 경로에 대한 공격 방어 성공은 pg알람에서 제외

- run_create_imagebuilder_gendo.py
- 기존 Gendo Image는 AWS CLI v2 설치를 이미지 빌더의 AWS에서 제공하는 component로 설치하는 형태 
- AWS 제공하는 Component가 우리가 모르는 부분을 설정함으로써 생기는 문제일 수 있어 직접 설치하는 방향으로 변경.
**연관 PR**
https://github.com/HardBoiledSmith/gendo/pull/774
- johanna에서 ./run_create_imagebuilder_gendo.py -b DEV-13352 를 실행해주세요.
- aws console에 접속하여 imgaebuilder 서비스로 들어가주세요.
- 실행한 스크립트의 이미지가 에러 없이 생성이 되어야 합니다.
> DEV-13352 gendo: EB에서 AWSCLI 관련 에러(Access violation)발생 원인파악 AWS CLI2 직접 설치로 변경.

- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_ses_sqs.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
- DEV-12682 모든 람다 플랫폼을 python3.7 에서 python3.8로 업그레이드
- kaji의 람다들을 AWS상에 프로비저닝 후 에러없이 정상 동작해야 합니다.
> DEV-12682 모든 kaji/lambda 를 python3.7 에서 python3.8로 업그레이드

- .gitignore
- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- Apple Silicon에서도 프로비저닝 및 이용 가능하도록 프로비저닝 코드를 재구성
- ARM64에선 https://app.vagrantup.com/hbsmith/boxes/fedora-35-aarch64를 이용하도록 구성
- x86 환경에선 기존과 동일하게 https://app.vagrantup.com/hbsmith/boxes/awslinux2 를 이용하도록 구성
- `ARCH=arm64 vagrant up`으로 M1 Mac에서 프로비저닝 정상 수행되는지 확인
- 기존 x86 맥에선 `vagrant up`하면 프로비저닝이 정상 수행되는지 확인
> DEV-13834 Apple Silicon (aarch64) 지원 추가

- run_create_imagebuilder_gendo.py
-  image builder에서 gendo image 파이프라인 구축을 위해 필요한 것 중 한 개인 component 요소에서 에러가 발생
- 원인 : 한개의 component( .yml ) 파일에는 16000자 제한
- 해결 방안: component를 둘로 쪼개어 설치를 진행
> johanna, gendo : imagebuilder gendo image 스크립트 수정 ( component 16,000자 제한으로 인해 파일 2개로 분리)

- run_create_eb_windows.py
- https://hbsmith.atlassian.net/browse/DEV-14678 [운영팀]storage 셋팅 메뉴발생 /  "Low disk space" 팝업 노출 테스트 실패 현상 후속 이슈
- row disk space 팝업이 뜨는 부분을 해소 하기 위함.
- master branch johanna를 띄워주세요.
- ssh johhanna에 접속 후 /opt/johanna으로 이동해주세요.
- ./run.py create_vpc
- ./run_create_eb.py  gendo를 실행해주세요.
- AWS console에 들어가 gendo가 정상적으로 생성되었는지 확인해주세요.
- EC2 서비스 탭에 들어가 Gendo에 연결된 볼륨 스팩을 봐주세요.
- 용량이 40GB 여야 합니다.
**EB**
**EC2** 
**gendo Volume**
> DEV-14684 Gendo : AWS EB Volum 30GB -> 40GB로 증설

- _provisioning/provisioning.py
- nameserver resolver 이슈로 프로비저닝이 실패하는 이슈 해결
- 참조) http://www.linux-databook.info/?page_id=5951
- 프로비저닝 정상 수행 확인: `vagrant up`
> DEV-14893 Fedora 3.3 이상 버전에서 nameserver resolver 동작 이슈 해결

- run_create_codebuild_common.py
- codebuild project 내에서 Parameter Store 에 박혀있는 AccessKey/SecretKey 사용 -> codebuild project에 Role기반으로 대체
해당 PR은 Code build `billing_backup_op_hbsmith_script_new` 의 정책을 반영하기 위해 스크립트를 수정하였습니다.
**참고 PR**
https://github.com/HardBoiledSmith/magi/pull/894
- 해당 브랜치의 johanna를 띄워주세요.
- 해당 브랜치의 magi/daily_cd 경로에 zip 파일을 압축 해제 해주세요.
- billing-config.json 값에 아래 스크린린샷 값을 복사하여 johanna 개인 dv config 파일에 codebuild 부분에 추가해주세요.
- 값의 경우 op는 master로 변경해주세요. (혹시 모를 부분을 위한 방지)
- johanna  run_create_codebuild_cron.py 파일에 아래 스크린샷을 주석처리해주세요. (일반 개인 계정에는 chatbot설정이 없어 exception이 남)
- ssh로 johanna vagrant 접속 후  opt/johanna로 이동 해주세요.
- ./run_create_codebuild.py -b DEV-15241 billing_backup_op_hbsmith_script_new 를 실행해주세요.
- 정상적으로 codebuild가 생성되어야 합니다.
op를 기준으로 작성 된 값이기 때문에 build는 실패 나는게 정상입니다.
통과를 시키려면 각 개발자의 환경에 맞게 …
> DEV-15241 billing 계정 IAM KEY 사용하는 자원 role 베이스로 전환

- run_create_codebuild_common.py
- codebuild를 만들 때 생성되는 권한에 STS를 써야하는 경우가 존재함. ( 타 계정에 대해선 STS를 통해 가져와야 함 )
- AWS CLI에서 STS를 사용 할 수 있도록 내용 추가.
**연관PR**
https://github.com/HardBoiledSmith/magi/pull/897
> DEV-15320 [OP패치 지원] billing 계정 IAM KEY 사용하는 자원 role 베이스로 전환 권한 적용

- run_create_imagebuilder_gendo.py
- 그대로 return을 하여 codebuild가 성공으로 나옴. Fail이 되도록 return 되는 코드를 제거.
- run_create_imagebuilder_gendo가 정상적으로 수행 되어야 합니다.
- 최신 버전이 아닐 경우 raise가 되어 Codebuild에서 Fail이 나야 합니다.
> DEV-15515 imagebuilder 생성 시 Error 발생 후 Fail 나도록 변경

- run_common.py
- run_create_eb_windows.py
- run_create_imagebuilder_ci_gendo.py
- run_create_imagebuilder_gendo.py
- run_terminate_imagebuilder_ci_gendo.py
- run_terminate_imagebuilder_gendo_old_environment.py
- ci gendo 스크립트
- 생성 : 매주 월요일 8시 실행
- 삭제 : 매주 목요일 8시 실행
- gendo 이미지 생성 스크립트
- 생성 : 패치 당일에 Merge가 된 후 별도로 실행.
- 삭제 : imagebuilder에 gendo관련 모든 자원 삭제 ( AMI 외에는 imagebuilder의 모든 자원을 조회하고 삭제하고 있기에 이 또한 수정되어야 함.)
- 오래된 버전 삭제 : 최신 생성 된 gendo 이미지 및 이미지 빌더 자원을 2개를 남기고 삭제를 시킴 
- magi에 오래된 버전 삭제에 대한 부분은 추가 X. 
- 사유 : 환경 분리를 명확히 한 후 서로 영향이 없도록 만들기 위함. 두 스프린트에 걸쳐 작업예정. 추가로 OP환경에서 사용되는 ami의 경우 삭제되지 않도록 방지책 추가 고민 필요 ( 사용되고 있는 AMI여도 삭제처리가 가능함 보호되지 않음 )
- 오래된 버전 삭제 및 gendo에 대한 자원 삭제에 대한 스크립트는 추가 보완이 필요 함. 
- https://hbsmith.atlassian.net/browse/DEV-16116 이슈에서 후속 이슈로 추가 작업 예정.
old_environment 스크립트의 경우 최신 2개에 대해 구성하다보니 코드를 어느정도의 복잡함이 있었습니다.
요약하면 아래의 수순으로 진행을 합니다.
1. 각 자원에 대해 모든 리소스 리스트를 조회함.
2. 모든 리스트들에 붙은 timestamp 값들을 정리함 (중복 제거)
3. imagebuilder에 완전하게 구성된 자원과 완전히 구성되지 않은 자원을 구분 함
4. 정상적으로 생성되지 않은 자원들의 …
> DEV-15833 imagebuilder 주기적으로 돌아가는 스크립트, 패치용 이미지 생성 스크립트 분리

- run_create_s3_vue.py
- OP환경에서는 DEV-11972 문제로 sourcemap을 S3에 업로드 안함
- sentry를 사용하지 않는 DV/QA 환경까지 sourcemap을 sentry에 업로드할 필요가 없음
- DV/QA 환경의 경우 sourcemap을 sentry업로드하지 않고, S3 버킷 또는 동일한 localpath에서 확인 가능하도록 수정
- 본 PR 적용 이후 QA 환경에서도 문제세 source 파악 및 디버깅 가능
- QA환경에서 S3 버킷에 *.map 파일이 존재하고 아래 스샷의 에러가 뜨지 않음을 확인
> DEV-15909 [app console 2.0] .map 파일을 못찾아 warning 발생

- run_create_eb_windows.py
- [gendo][hoftix] 비용절감을 위한 gendo 스케일링 정책 조정
- 2023.1.4 스크럼 회의에서 논의한 방향대로 진행했습니다.
- 오전 7시에 인스턴스 생성
- 오후 10시 인스턴스 축소
- 개발환경에 따라 분기를 타도록 해야하나 고민했으나, OP환경과 값은 다를 수 있어도 환경은 동일하게 구성해야 테스트가 될 수 있기에 환경에따른 분리를 하지 않았습니다.
**관련 PR**
https://github.com/HardBoiledSmith/magi/pull/1002
- 논의한 방향
오전 7시에 늘리기 작업
오후 10시에 줄이기 작업
- 최소 최대 조절량을 1로 설정해도 잘 생성되는 부분 확인했습니다 ( 개발환경의 경우 세팅을 1로 할 예정)
> DEV-17298 [gendo][hoftix] 비용절감을 위한 gendo 스케일링 정책 조정

- run_common.py
- run_create_eb_windows.py
- DEV-17638 [gendo] HotFix: 스케일링 정책 수정
- scale out 조건 5 → 60으로 변경
- Time Base 스케줄 조정 조건 한 개 추가 
**연관PR**
https://github.com/HardBoiledSmith/magi/pull/1018
- 해당브랜치의 johanna, magi 파일 압축해제.
- ./run_create_vpc.py , ./run_create_eb.py gendo 실행 시 이상이 없어야 하고 아래 스크린샷 처럼 반영이 되었는지 확인.
Time Base 스케줄 조정 한 개 추가 ( 자정 15대 )
5 -> 60으로 변경
> DEV-17638 [gendo] HotFix: 스케일링 정책 수정

- run_create_cloudwatch_dashboard.py
- Cloudwatch Gendo Metric 대시보드 추가 (HealthyHostCount, UnHealthyHostCount)
- 과거 기록까지 확인 가능하도록 구성.
**연관 PR**
https://github.com/HardBoiledSmith/magi/pull/1038
환경 세팅
- ./run_create_vpc.py
- ./run_create_eb.py gendo
- ./run_create_cloudwatch_dashboard.py -b DEV-17456 gendo
- 대시보드에 정상적으로 과거 모든 ELB지표에 있는 Healthyhost, unHealthyhost가 있는지 확인해주세요.
> DEV-17456 Cloudwatch Gendo Metric 대시보드 추가 (HealthyHostCount, UnHealthyHostCount)

- run_create_eb_windows.py
- DEV-17879 [gendo] 매직넘버 수정: 평일 15~60대선으로 운영, 주말 15~40대선으로 운영
autoscale 시간 기준이 UTC이므로 이에맞춰 cron 스케줄 설정. 평일 주말로 나뉨에 따른 time base autoscale 코드 수정.
평일 : 월 - 금  // out 60 in 15
주말 : 토 - 일 // out 40대 in 15
> DEV-17879 [gendo] 매직넘버 수정: 평일 15~60대선으로 운영, 주말 15~40대선으로 운영

- run_common.py
- EB window platform version update 2.11.3 -> 2.11.4
출처 : https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
- EB python은 업데이트 된 버전이 없어 반영하지 않았습니다.
- imagebuilder 서비스 Gendo 이미지 생성 성공
> DEV-18501 EB window platform version update 2.11.3 -> 2.11.4

- run_create_route53_health_check.py
- run_terminate_route53_health_check.py
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요
- 참조
- [johanna](https://github.com/HardBoiledSmith/johanna/pull/721)
- [magi](https://github.com/HardBoiledSmith/magi/pull/1092)
- [ws-scrcpy](https://github.com/HardBoiledSmith/ws-scrcpy/pull/159)
- magi 설정 생성 및 johanna에 설정 복사
- sns --> ramiel --> `"NAME": "ramiel-status-notification",` 를 포함한 dict 있는지 확인
- route53 --> ramiel --> `"NAME": "ramiel",` 항목 확인 --> 해당 항목에 `"TARGETDOMAINNAME_LIST": "idc-yatab-1.hbsmith.io:28500,idc-yatab-2.hbsmith.io:28501",` 설정
- johanna 배포: `BRANCH=DEV-18626 vagrant up`
- aws 자산 배포
- sns: `./run_create_sns.py -f ramiel-status-notification`
- cloudwatch alarm, route53 상태 점검: `./run_create_route53_health_check.py -f`
- 생성 자원 확인
- aws --> sns --> 
- aws --> route53 --> 상태 점검
- aws --> cloudwatch --> 알람
- 확인 …
> DEV-18625 [라미엘] 응답없는 맥미니 cloudwatch - pagerduty 알람 모니터링 추가

- README.md
- run_create_route53_health_check.py
- run_terminate_route53_health_check.py
- route53 health check 부분 배포/정리 기능 추가
- 참조
- https://github.com/HardBoiledSmith/magi/pull/1105
- https://github.com/HardBoiledSmith/johanna/pull/728
- 배포
- magi에서 DEV-19042 체크아웃 --> 개인 seele 압축 해제 --> route53 --> ramiel에 내용 변경:`"TARGETDOMAINNAME_LIST": "idc-yatab-1.hbsmith.io:28500,idc-yatab-2.hbsmith.io:28501,idc-yatab-2.hbsmith.io:28502,idc-yatab-2.hbsmith.io:28503",` --> johanna에 config.json 복사
- johanna를 DEV-19042로 배포
- johanna에 ssh 접속
- route53 health check 부분 배포: ./run_create_route53_health_check.py ramiel -f
- AWS 콘솔 확인
- route53 health check 부분 삭제: ./run_terminate_route53_health_check.py ramiel -f
30 x 10 으로 민감도 연장 확인
> DEV-19042 [라미엘] Route53 health checker 민감도 조정

- run_common.py
- run_create_eb_django.py
- DEV-19640 eb gendo platform version update 2.11.8 -> 2.12.0
- 참고 : https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.net
- code build ( billing_create_gendo_image )가 성공 해야 합니다.
> DEV-19640 eb gendo platform version update 2.11.8 -> 2.12.0

- run_create_eb_django.py
- 64bit Amazon Linux 2 v3.5.7 running Python 3.8 솔루션 스택 deprecation 해결
- `./run_create_eb_django.py sachiel` 배포 성공
> DEV-19978 64bit Amazon Linux 2 v3.5.7 running Python 3.8 솔루션 스택 deprecation

- run_create_eb_windows.py
- c6i.large -> c7i.large 업그레이드 진행
- 서울리전 OP 계정 지원여부 확인
```
aws ec2 describe-instance-types \
--filters "Name=instance-type,Values=c7i.large" \
--query "InstanceTypes[*].{InstanceType:InstanceType,VCpuInfo:VCpuInfo,MemoryInfo:MemoryInfo}" \
--profile hbsmith-op \
--output table
-------------------------------------------------------------
|                   DescribeInstanceTypes                   |
+-----------------------------------------------------------+
|                       InstanceType                        |
+-----------------------------------------------------------+
|  c7i.large                                                |
+-----------------------------------------------------------+
||                       MemoryInfo                        || …
```
> DEV-20642 [gendo] C7i 업그레이드 진행

- run_create_lambda_cron.py
- DEV-21067 [kaji] sachiel_send_slack_slow sleep 로직 수정 이슈 진행간 발견 된 run_create_lambda_cron 버그 코드 수정
- 현재 아키텍처 구조에서 currency 값을  사용하고있는 코드는 없어 발견되지 않음
- 업데이트 시 currency 값을 참고하여 업데이트하는 부분이 누락되어 있어 코드 추가.
- currency를 0으로 세팅하려 할 경우 업데이트 코드가 실행되지 않음. 따라서, 0의 숫자여도 실행이 가능하도록 None이 아닌 경우에만 실행 되도록 변경진행.
- Johana를  통해 Lambda가 정상적으로 생성 되어야 합니다.
> DEV-21067 [kaji] sachiel_send_slack_slow sleep 로직 수정 이슈 진행간 발견 된 run_create_lambda_cron 버그 코드 수정

- run_create_eb_windows.py
- run_terminate_eb_old_environment.py
- gendo graceful shutdown 적용
- gendo cname 교체 타이밍을 모든 인스턴스가 생성 된 후 변경되도록 함.
- 자체적으로 최신버전이 아닌경우 Gendo가 직접 죽는 코드를 추가함에 따라 johanna에서 desired capacity를 낮추는 코드 제거
- eb_old_environment 코드에 gendo가 0대가 되었을 떄 정리되도록 변경
**연관 PR**
https://github.com/HardBoiledSmith/gendo/pull/1749
- ./run_create_vpc.py
- ./run_create_rds.py
- ./run_create_ec2_client_vpn.py
- 데이터베이스 리셋
- ./run_create_eb.py sachiel
- ./run_create_eb.py gendo -b DEV-21310
- ./run_create_s3.py
- ./run_create_sqs.py
- ./run_create_lambda.py sachiel_send_visual_test_result_get_1_ap-northeast-2
**최신 버전이 아닌 경우 0대로 변경됨에 따라 No Data노출**
> DEV-21310 Gendo Graceful shutdown 방지 코드 설계 방안 검토 및 적용

- run_create_eb_windows.py
- 간헐적으로 발생하는 `You must specify a region. You can also configure your region by running "aws configure".` 에러를 해결시도.
- 강제로 AWS_DEFAULT_REGION, AWS_REGION을 환경변수로 설정. boto3나 aws cli가 이를 이용하도록 함
- 연관 PR: https://github.com/HardBoiledSmith/gendo/pull/1814
- 정상적으로 프로비저닝 되어야 함
- 정상적으로 스크립트 다운로드, 테스트 수행, 결과 업로드 되어야 함
> DEV-21827 [gendo] You must specify a region. You can also configure your region by running "aws configure".

- run_create_eb_windows.py
- 구버전 Gendo가 종료되지 않고 스크립트들이 실행되고 있는 현상 발견.
- Gendo 환경 교체 되면서 구 버전은 0대로 만들어졌으나, 구 버전 환경 정리 코드가 실행 되기 전 인스턴스 갯수 스케줄링으로 인해 갯수가 늘어나 구버전이 정리되지 않음.
- 환경 교체 후 0대로 줄이기 전 구버전 Gendo에 대한 instance 조정 trigger 이벤트들을 삭제 하도록 함.
- Gendo 인스턴스 수 조절 관여하는 서비스는 (Cloudwatch, Auto Scaling Group) 에 있습니다.
- aws 환경 구성해주세요.
- run_create_vpc.py
- run_create_eb.py gendo
- 생성 완료 후 cloudwatch, autoscaling group에 걸려있는 스케줄 베이스 조정 정책이 있는지 확인합니다.
- run_create_eb.py gendo
- 실행하여 교체 후 구버전 Gendo에 대한 instance 관련 작업이 모두 삭제 되어 있는지 확인해주세요.
> DEV-21876 [Gendo] 구버전 Gendo에서 테스트가 돌아가는 현상 조사

- run_create_route53_health_check.py
- DEV-22291 datetime 관련 deprecated 해결
**케이스 1**
datetime.utcnow() → datetime.now(timezone.utc) 으로 변경
**케이스 2**
a = datetime.now(timezone.utc)
b = datetime.strftime("") (timezone 없음)
- 기존 기능들에서 에러없이 동작 해야 합니다
> DEV-22291 datetime 관련 deprecated 해결

- run_terminate_imagebuilder_gendo_old_environment.py
- [AWS] billing 계정 imagebuilder 오래된 자원 자동삭제 코드 점검
**원인**
- 각 자원의 list 조회 시 max가 25개로 제한되어있음. abnormal 판단을 할 때 component에서 전체가 넘어오지 않아 2025년도의 자원을 비 정상으로 판단을 함 현재 버전은 사용중이기에 필터 대상에서 제외가 됨.
- 이에따라, next token을 이용하여 전체 자원을 조회 하도록 변경 함.
- johanna에서 ./run_terminate_imagebuilder_gendo_old_environment.py를 실행해주세요.
- 자원이 8주 를 초과한 자원은 삭제가 되어야 합니다.
- 비정상적인 자원 ( 파이프라인, 이미지, 레시피등 필수구성요소가 없는 자원) 은 삭제 되어야 합니다.
> DEV-23132 [AWS] billing 계정 imagebuilder 오래된 자원 자동삭제 코드 점검

- run_common.py
- run_create_imagebuilder_gendo.py
-  imagebulider requirements.txt 패키지 설치 실패 시 이미지 생성 실패되도록 코드 수정 필요
- 패키지 정상 설치가 되지 않았음에도 이미지가 생성되어 서버 생성전까지 인지를 하지 못햇음.
- 이에따라, 패키지 버전 설치 시 에러발생한 경우 이미지 빌드 실패되도록 코드 변경함.
https://github.com/HardBoiledSmith/gendo/pull/1985
- ./run_create_imagebuilder_gendo.py -b DEV-23220을 실행해주세요.
- 테스트 실패를 확인하기 위해선 requirement.txt에 설치가 실패하는 버전으로 수정해야합니다.
> DEV-23220 imagebulider requirements.txt 패키지 설치 실패 시 이미지 생성 실패되도록 코드 수정 필요
