HardBoiledSmith/johanna

- run_create_s3.py
- run_terminate_s3.py
- Fix invalid settings reference at run_template_s3.py 
- Reformat code run_create_s3.py
> GEN-768 Fix provisioning failure

- run_common.py
- run_create_vpc.py
- run_terminate_vpc.py
This feature created for naverlabs
@addnull Please review
> GEN-1461 Add support for multiple VPCs in same account

- requirements.txt
> GEN 2874 Update python library version

- run_create_eb_openvpn.py
- magi 에 있는 설정을 penpen 으로 옮겨 그에 맞고 openvpn eb 생성 코드를 수정 하였습니다.
> GEN-3507 Fix create openvpn eb

- run_create_eb_django.py
- run_create_eb_openvpn.py
- elastic beanstalk version 업데이트(`64bit Amazon Linux 2018.03 v2.7.7 running Python 3.6` -> `64bit Amazon Linux 2018.03 v2.8.1 running Python 3.6`)
> GEN-4036 Update elastic beanstalk version

- aws_iam/aws-codebuild-secure-parameter-policy.json
- aws_iam/aws-codebuild-secure-parameter-role.json
- run_create_codebuild.py
- run_create_codebuild_github.py
- run_terminate_codebuild.py
- github build 테스트를 하는 codebuild 생성하는 것 추가
> GEN-4018 Add create codebuild integration github

- buildspec.yml
- run_create_codebuild_cron.py
- run_create_codebuild_default.py
- run_create_codebuild_github.py
- run_terminate_codebuild.py
Codebuild 로 빌드 테스트 할 수 있게 buildspec 추가
> GEN-4188 Add buildspec script for build test by codebuild

- run_create_codebuild_github.py
- window 용 codebuild 생성 하기 위해 `container_type` 을 추가함
- 빌드후 파일 업로드를 위해 `artifacts` 를 추가함
> GEN-3996 Fix to build in windows

- run_create_cloudwatch_dashboard.py
- 클라우드 와치 알람 위젯 한줄에 4개 씩 세팅되도록 수정
> GEN-4402 Fix cloudwatch alarm 4 in one line

- run_create_codebuild_github.py
- secondaryArtifacts 추가 하는 부분 추가
> GEN-4539 Add secondaryArtifacts option

- run_create_eb_django.py
- run_create_eb_openvpn.py
Elasticbeanstalk platform version을 업그레이드했습니다.
> GEN-4960 Update EB platform version

- aws_s3/aws-s3-bucket-policy-for-email.json
- run_create_s3_bucket.py
> GEN-5066 Fix to add email bucket

- run.py
- s3 에 의존성 때문에 ses 생성을 나중으로 변경
> GEN-5389 create ses last

- _provisioning/requirements_rpm.txt
- run_create_eb_windows.py
- git hash 를 사용해 최신 빌드 파일을 받도록 수정
> GEN-5598 Add download build file

- run_create_codebuild_github.py
- run_terminate_codebuild.py
- 기존 github codebuild 에 cron 기능을 추가로 설정 할 수 있도록 수정
> GEN-5558 Add cron feature to github codebuild

- run_export_cloudwatch_dashboard.py
- `run_create_cloudwatch_dashboard.py` 생성된 cloudwatch dashboard 를  `run_export_cloudwatch_dashboard.py` 추출 하면 달라지는 버그가 있어서 수정
- 운영(op)의 설정값을 넣고, `run_export_cloudwatch_dashboard.py` 실행후 필드에 들어가면 안되는 값 intance id 혹은 name, loaderbalancer 값들이 맞는 변수 명으로 대치 되었는지 파악
> GEN-5888 Fix export cloudwach dashborad to sync create

- run_terminate_rds.py
- PyCharm Inspect Code 검사 및 warning 수정 또는 ignore 처리
- pycharm 내에서 Inspect Code 검사
이 전에 nerv python에 대해 Inspect Code 검사를 한 적이 있어 python은 수정할 것이 없었습니다.
javascript부분을 검사하였습니다.
> GEN-6018 Johanna Inspect Code

- _provisioning/requirements_rpm.txt
> QA Merge: W45 1st

- _provisioning/requirements_rpm.txt
- codebuild 생성/제거중 예외가 발생하여 실행이 안되는 버그를 해결
> QA Merge: W45 2nd

- _provisioning/requirements.txt
- requirements.txt
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요
- codebuild에 해당 저장소 내용이 없어 `miscellaneous`으로 패키지 최신 버전 확인
- run_terminate_eb를 통해 awscli 버전 업데이트가 문제 없는 지 확인
requests 모듈은 사용하는 곳이 없는 것 같은데, _provisioning에 requirements.txt 존재 이유를 잘 모르겠네요..
> GEN--6639 package update

- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_windows.py
-elastic beans talk 버전 업데이트
https://github.com/HardBoiledSmith/johanna/blob/cf1ead085ad29df7d63dbe15636bd0311b6b46a4/run_create_eb_spring.py#L346
저희 회사에서 Spring은 사용하지 않는 것으로 알고 있는데 해당 파일도 버전 업데이트가 필요할까요?
https://docs.aws.amazon.com/ko_kr/elasticbeanstalk/latest/platforms/platforms-supported.html
> GEN-6663 elastic beanstalk version update

- run_create_eb_django.py
- run_create_eb_openvpn.py
- QA Merge: W49 2nd Update version number for EB
> QA Merge: W49 2nd Update version number for EB

- run_create_eb_windows.py
- Update version number for EB
> QA Merge: W47/48 3rd Update version number for EB

- run_create_appstream.py
- run_terminate_appstream.py
- appstream 을 띄울수 있게 추가함
- `run_create_appstream.py <image-builder name>` 실행 해서 image builder 를 띄워야 함
- 해당 image builder 사용해 이미지를 생성
- `run_create_appstream.py <stack name>` 실행 하면 됨
- 예제 템플릿
```
"appstream": {
"IMAGE_BUILDS": [
{
"NAME": "some-builder",
"SUBNET_TYPE": "public",
"IMAGE_NAME": "AppStream-WinServer2016-09-18-2019"
}
],
"STACK" : [
{
"NAME": "some-stack",
"FLEET_NAME": "some-fleet",
"IMAGE_NAME": "some-windows",
"SUBNET_TYPE": "public"
}
]
}
```
> GEN-6809 Add appstream

- run_create_cloudwatch_alarm.py
- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_windows.py
> QA Merge: 2020 W1

- run_create_appstream.py
- appstream 에서 stack 생성시 종료후 redirect 될 url 넣어 주는 옵션을 추가함
- appstream 에서 stack 생성후 옵션 값에 넣어준 redirect url 들어가 있으면 성공
> GEN-7501 Add redirect url option

- run_create_eb_windows.py
- eb windows 의 solution stack version 업데이트
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)
> GEN-7469 fix eb window solution stack version

- run_terminate_sns.py
- Ignore error when sns topic is deleted
> QA Merge: [HotFix] Ignore error when sns topic is deleted

- run_create_appstream.py
- appstream embed에 필요한 host domain url 추가하는 코드 추가하였습니다.
- johanna에서 setting 값을 추가해야 합니다.
@yoonjs2 // config.json 값 변경 요청드리겠습니다
> GEN-7865 run_create_appstream.py  / domain-host-url 옵션 추가

- run_create_eb_windows.py
- run_terminate_sns.py
> QA Merge: W4/5

- run_create_eb_django.py
- run_create_eb_windows.py
- QA Merge: W4/5 Update eb platforms
> QA Merge: W4/5 Update eb platforms

- run_create_eb_openvpn.py
- QA Merge: W4/5 Update platform version
> QA Merge: W4/5 Update platform version

- run_create_appstream.py
- QA Merge: W4/5 Fix network settings for appstream
> QA Merge: W4/5 Fix network settings for appstream

- run_create_appstream.py
- 기존 public 영역에 있었던 부분을 private로 변경
- DV, QA 환경 테스트는 완료했습니다 25일 OP환경 테스트 예정입니다.
테스트 방법은 iam, vpc 생성 후 appstream을 생성하여 테스트 진행하면 됩니다.
web까지 진행하고자 한다면 iam, vpc, rds, penpen을 띄운 후 rds에 데이터를 밀어 넣은 후 sachiel , appstream, s3 를 띄우시면 필요한 부분까지 테스트 가능합니다.
> GEN-8307 appstream subnet & security group setting change public -> private

- _provisioning/provisioning.py
- _provisioning/requirements.txt
- _provisioning/requirements_rpm.txt
- requirements.txt
- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_windows.py
- rpm, npm package 버전 업데이트
- https://hbsmith.atlassian.net/browse/GEN-8738 pip3 upgrade 추가 
- https://hbsmith.atlassian.net/browse/GEN-8570 eb platform update
- git pull 이후 vagrant up을 해주세요.
- pip upgrade 경고문이 나오는지 확인해주세요.
- 제대로 provisioning이 되었는지 확인해 주세요.
- johanna에서 ./run.py create_iam & create_rds & create_vpc & create_eb 총 4개를 실행시켜주세요. 환경이 잘 뜨는지 확인해 주세요.
업데이트 된 platform으로 생성하는 환경 볼 수 있습니다.
> GEN-8268 package update

- _provisioning/provisioning.py
- _provisioning/requirements.txt
- _provisioning/requirements_rpm.txt
- requirements.txt
- run_create_cloudwatch_alarm.py
- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_windows.py
> QA Merge: W9 2nd

- run_create_codebuild_github.py
- run_create_eb.py
- run_create_eb_windows.py
- run_create_ec2_keypair.py
- run_create_s3_vue.py
- run_describe_cloudwatch.py
- run_describe_vpc.py
- run_terminate_eb.py
- run_terminate_lambda.py
- string formatting을 f-string으로 통일
- 기본 python3 코드로 일치하는 지 테스트
- 일부 johanna코드 실행
> DEV-8432 Refactor Format String

- run_create_appstream_fleet_autoscale.py
- run_create_appstream_stack_fleet.py
- run_terminate_appstream_fleet_autoscale.py
- Appstream auto scale 적용
- Appstream stack 및 fleet를 생성해 주세요. 
- 생성이 되었다면 ./run_create_appstream_fleet_autoscale.py 를 실행해 주세요.
- Cloudwatch에 들어가 Appstream 탭을 가보면 확인 하실 수 있습니다.
- 테스트가 끝났다면 자원을 정리해주세요.
johanna config.json값을 입력해야 합니다. 테스트 요청 시 데이터 드리겠습니다
> DEV-8798 Appstream Auto scale 적용

- run_common.py
- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_spring.py
> QA Merge: W12/13 2nd

- run_create_eb_django.py
- run_create_eb_openvpn.py
- run_create_eb_windows.py
> QA Merge: 12/13 2nd

- run_create_appstream_stack_fleet.py
- QA Merge: W12/13 Fix parameter problem
> QA Merge: W12/13 Fix parameter problem

- run_create_appstream_stack_fleet.py
- QA Merge: W12/13 Add support naoko-windows-*
> QA Merge: W12/13 Add support naoko-windows-*

- run_create_appstream_stack_fleet.py
- QA Merge: W12/13 Fix wrong command
> QA Merge: W12/13 Fix wrong command

- run.py
- run_create_cloudwatch_dashboard.py
- run_create_codebuild.py
- run_create_eb_openvpn.py
- run_create_ec2_keypair.py
- run_create_lambda_default.py
- run_create_lambda_sqs.py
- run_create_sqs.py
- run_terminate_cloudwatch_dashboard.py
- 미전환 된 곳 f-string 으로 전환
- 기본 python3 코드로 일치하는 지 테스트
- 일부 johanna코드 실행
> DEV-8934 Reformat to f-string (continued)

- run_create_eb_openvpn.py
- f string 에 string fomate 이 같이 쓰여 에러 발생 되서 f string 만 쓰도록 수정
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요
> DEV-9056 fix wong syntax(string format with f string)

- README.md
- run_create_s3_srr.py
- run_terminate_s3_srr.py
- qa-hbsmith-script-new 버킷으로 복제된 파일의 Owner 세팅이 날아가 있어 다운로드가 안되는 문제가 있음 
- Readme.md의 srr 세팅법을 따라 세팅 후 s3에 옵션이 잘 되었는지 확인 및 파일 업로드
> DEV-8999 run_create_s3_srr / 복제된 파일 소유주 변경

- run_create_s3_script_lifecycle.py
- run_terminate_s3_script_lifecycle.py
- Deep QA script 파일을 변경할 시 불필요한 파일 관리를 위해 s3 버킷에 lifecycle 정책 적용.
- 적용할 s3 bucket을 생성 해 주세요. 
- 해당 스크립트를 실행 시켜주세요. (각 파라메터에 값 입력)
- aws 콘솔에 들어가 s3 에 lifecycle이 잘 적용 되었는지 확인해 주세요.
> DEV-9013 S3 업로드 되고 사용 하지 않은 스크립트 삭제 처리 #2

- _provisioning/provisioning.py
> DEV-9123 Remove pip Path Warning

- run_common.py
- run_create_appstream_builder.py
- run_create_appstream_fleet_autoscale.py
- run_create_appstream_stack_fleet.py
- run_create_eb_django.py
- run_create_eb_windows.py
- run_terminate_appstream_builder.py
- run_terminate_appstream_fleet_autoscale.py
- run_terminate_appstream_stack_fleet.py
- DEV-9317 Add ap-southeast-1 as region
> DEV-9317 Add ap-southeast-1 as region

- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- _provisioning/requirements_rpm.txt
- vagrant & vagrant 쪽 provisioning.py 스크립트를 amazon linux 2로 전환
- run_create_sqs.py 실행 후 확인
- run_terminate_sqs.py 실행 후 확인
> DEV-9233 Migrate johanna to Amazon Linux 2

- run_create_eb_windows.py
- QA Merge: W20/21 Update window eb platform version
> QA Merge: W20/21 2nd

- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
> QA Merge: W20/21 3rd

- run_create_eb_django.py
- Deep Learning 서버인 shamshel 설정을 추가
- 현재 개발중이므로 merge는 안정화 된 후에 진행하겠습니다.
> DEV-9252 (in-progress) Add shamshel settings

- run.py
- run_codebuild_wait_done.py
- run_create_codebuild.py
- run_create_codebuild_vpc.py
- run_reset_database.py
- run_terminate_codebuild.py
- run_terminate_codebuild_vpc.py
- codebuild 를 사용해 초기 database 생성후 기본 데이터를 넣어 주는 codebuild 생성 하는 기능 추가
> DEV-9286 Codebuild 를 통해 database 를 init 할 수 있는 기능 추가

- run_codebuild_wait_done.py
> DEV-9447 wait build status not in progress

- run_create_ec2_keypair.py
- format 을 f-string 으로 바꾸는 도중 실수가 있었던 것 같아 수정 했습니다.
- run_create_ec2_keypair.py 실행시 문제 없이 실행 되면 성공
> DEV-9494 잘못된 문법 수정

- run_create_s3_vue.py
- 아래 PR들과 연계하여 sentry release 정보를 배포시 추가합니다.
- https://github.com/HardBoiledSmith/hbsmith-web/pull/817
- https://github.com/HardBoiledSmith/magi/pull/605
- ./run_create_s3.py 를 통해 vue app 들이 정상적으로 배포되고, sentry에서 https://docs.sentry.io/workflow/releases/?_ga=2.72640275.1268343346.1572617831-1591963020.1572617831&platform=javascript#configure-sdk 처럼 release 정보가 확인 가능하면 OK
> DEV-6500 Add sentry cli command

- run_common.py
- run_reset_template.py
- reset_template 커맨드를 재개발하였습니다
- `reset_template_dir()`이라는 함수가 존재해서 이 함수를 그대로 가져와 사용하였습니다.
- run_reset_template.py 안에 위의 함수 내용을 집어 넣을까 고민했는데, 일시적인 import가 많아져서 우선은 그대로 위의 함수를 가져와 사용했습니다. 적절한 구조가 어떤 것인지 의견 부탁드립니다 🙏🙏🙏
- `./run.py reset_template` 커맨드 실행 후 template 폴더 내의 magi template이 새로 생성되는지 확인해주세요
> DEV-9417 reset_template 커맨드 재개발

- run_create_s3_script_lifecycle.py
- S3 업로드 되고 사용하지 않는 스크립트 파일이 삭제처리 된 이 후 해당 파일이 완전히 사라지기 까지에 대한 설정 파일 입니다.
통합하는 과정은 해당 PR이 merge 된 후 잘 되는 것을 확인되면
https://hbsmith.atlassian.net/browse/DEV-9157 이슈로 작업하도록 하겠습니다.
연관 된 PR
https://github.com/HardBoiledSmith/kaji/pull/508
https://github.com/HardBoiledSmith/sachiel/pull/573
> DEV-9228 S3 업로드 되고 사용 하지 않은 스크립트 삭제 처리 

- run_create_acm_certificate.py
- run_create_sqs.py
- run_reset_database.py
- run_terminate_acm_certificate.py
- run_terminate_sqs.py
- SQS 와 ACM 을 다른 리전에서 띄울 수 있도록 수정
- run_reset_database.py 에 phase 가 dv 이 브랜치를 dv 를 바라봄으로 master 를 바라보도록 수정
- ACM 을 아래 설정에 맞는 값을 넣어서 생성
```
"acm": [
{
"AWS_DEFAULT_REGION": "ap-southeast-1",
"NAME": "<domain name>",
"DOMAIN_NAME" : "<domain name>,
"ADDITIONAL_NAMES": [
"<domain>"
],
"VALIDATION_METHOD": "EMAIL"
}
]
```
- SQS 을 아래 설정에 맞는 값을 넣어서 생성
```
"sqs": [
{
"AWS_DEFAULT_REGION": "ap-southeast-1",
"DELAY_SECONDS": "0",
"NAME": "<queue name>",
"RECEIVE_COUNT": "3",
"RECEIVE_MESSAGE_WAIT_TIME_SECONDS": "0",
"RETENTION": "345600",
"TIMEOUT": "180",
"USE_REDRIVE_POLICY": "True"
}
],
```
> DEV-9407 SQS 와 ACM 을 다른 리전에서 띄울 수 있도록 수정

- run_create_eb_windows.py
HardBoiledSmith/gendo#290 를 op에서 사용하기 위한 설정 값 추가
- config.json 에 따른 run_create_eb_windows.py 내 gendo_cli.exe.config 생성 확인
- gendo_cli.exe.config 파일 내 <Dsn value=""/> 항목에 magi에서 설정한 변수 값이 정상적으로 작성 되는지 확인
> DEV-6601 gendo Sentry 탑재를 위한 설정 항목 추가

- run_create_appstream_stack_fleet.py
- run_terminate_appstream_stack_fleet.py
- naoko에서 credential을 role 기반으로 사용 하도록 변경.
- Appstream Embed 환경까지 띄워주세요. ( iam, vpc, rds, sachiel, hbsmith web, appstream)
- embed로 접속하여 스크립트 녹화 후 업로드 하여주세요.
> DEV-9428 Appstream-Naoko: AWS Role base로 API 사용

- run_common.py
- run_create_rds.py
- run_terminate_rds.py
> QA Merge: W28/29 1st

- run_create_appstream_stack_fleet.py
- run_terminate_appstream_stack_fleet.py
> QA Merge: W28/29 3rd

- _provisioning/requirements_rpm.txt
- johanna python3-dev 패키지 업데이트가 필요하여 적용된 부분 PR
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)
> DEV-9962 requirement.txt update

- run_create_eb_windows.py
- magi gendo -> BRANCH 설정에 따른 aws eb provisioning (https://github.com/HardBoiledSmith/magi/pull/643)
- 변경사항
1) gendo 프로젝트 구조, 프로비저닝 변경에 따른 aws eb 설치 진행 (https://github.com/HardBoiledSmith/gendo/pull/330)
1) gendo 중 특정 브랜치에 해당하는 코드 및 artifact 다운로드 후 aws eb에 설치 진행
> DEV-9893 프로젝트 구조, namespace, 프로비저닝 수정

- run_create_eb_django.py
- https://hbsmith.atlassian.net/browse/DEV-10281 에 언급된, AWS에서 요청하는 옵션 활성화를 추가
- johanna에서 사용중인 ec2 profile은 managed 세팅이라 수정 불필요
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/health-enhanced.html?icmpid=docs_elasticbeanstalk_console#health-enhanced-authz
- 2020년 11월 30일 이후 DailyCD가 문제없이 수행되고 EnhancedHealthAuthEnabled 옵션이 true로 활성화 되는지 확인
> DEV-10281 Add option_settings: EnhancedHealthAuthEnabled

- run_create_eb_windows.py
> QA Merge: W42/43 2nd

- run_create_codebuild_cron.py
- run_create_codebuild_default.py
- run_create_codebuild_github.py
- run_create_codebuild_vpc.py
- 빌드시에 수동으로 source version을 지정해줘야 하는 문제 해결
- default 로 source version이 들어감
> QA Merge: Codebuild: Specifies default source version

- _provisioning/provisioning.py
- run_create_vpc.py
- AWSCLI v2룰 사용하도록 합니다. (v1은 강제로 삭제합니다)
- `aws --version`으로 아래와 같이 버전이 찍히는지 확인합니다.
```
aws-cli/2.0.61 Python/3.7.3 Linux/4.14.200-155.322.amzn2.x86_64 exe/x86_64.amzn.2
```
- johanna의 주요 기능이 정상 동작하는지 확인합니다.
> DEV-10481 Force upgrade to awscliv2

- README.md
- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- Parallels Desktop 으로 가상머신을 migration 합니다.
- Parallels Desktop + vagrant + parallels vagrant plugin 으로 환경 구성후 vagrant up이 정상적으로 이루어지는지 확인
> DEV-10477 Migrate to parallels desktop

- _provisioning/provisioning.py
- run_create_eb_django.py
- run_create_eb_windows.py
- DEV-10662 배포를 위해 johanna를 최신 platform으로 업데이트
> QA Merge: [HotFix] DEV-10662

- _provisioning/provisioning.py
- run_create_eb_django.py
- run_create_eb_windows.py
- run_create_vpc.py
- DEV-10662 배포를 위해 johanna를 최신 platform으로 업데이트
> OP Merge: [HotFix] DEV-10662

- _provisioning/requirements.txt
- requirements.txt 에 명시된 패키지 버전 업데이트
- application 이 정상적으로 작동해야 합니다.
- Vagrant Provisioning 이 성공해야 합니다.
> DEV-10441 `requirements.txt` 업데이트

- run_create_lambda.py
- run_create_lambda_ses_sqs.py
- run_terminate_lambda.py
- 관련된 이슈 : https://github.com/HardBoiledSmith/kaji/pull/578
- SQS 와 SES를 사용하는 경우 템플릿을 lambda.py 안에서 핸들링하였을 때 생기는 이슈를 해결합니다.
```
{
"AWS_ACCESS_KEY_ID": "<🔑>",
"AWS_DEFAULT_REGION": "ap-northeast-2",
"AWS_SECRET_ACCESS_KEY": "<🔑>",
"DESCRIPTION": "sachiel - Send Email",
"EMAIL_BCC": "byun@hbsmith.io",
"EMAIL_FROM": "byun@hbsmith.io",
"GIT_URL": "git@github.com:HardBoiledSmith/kaji.git",
"NAME": "sachiel_send_email",
"SQS_NAME": "dv-hbsmith-email",
"TYPE": "ses_sqs"
}
```
Type 을 `ses_sqs` 로 변경합니다. SES 와 SQS 를 모두 사용하기 때문에 위와 같이 명명하였습니다. 
- 현재 HBsmith 는 us-east-1 리전으로 SES를 사용하고 있습니다. 이는 config 파일의 AWS_DEFAULT_REGION 을 따르지 않게 됩니다. 따로 정의할 수 있는 필드를 config 파일 안에 정의할 수도 있겠지만, SQS 와 같은 서비스의 리전도 정의하지 않기 때문에 일관성을 위하여 일단, johanna 코드 안에 'us-east-1' 을 사용하는 aws_cli 객체를 하나 더 만들어 사용하였습니다.
**a. `templates/` …
> DEV-8945 SES를 사용하는 Lambda 의 경우 Template 생성을 분리하여 처리하도록 함.

- run_common.py
- run_create_eb_django.py
- ELB에서 502 Bad Gateway 에러가 하루에 최소 1회 이상 발생중 (8월부터)
- 이의 원인 분석을 위해서 ELB 로깅을 활성화 함
- 원인 파악되면 비용 절감을 위해 해당 기능은 disable 처리할 예정
- https://github.com/HardBoiledSmith/sachiel/pull/681 와 짝이슈
- sachiel 이 provisioning 되면 ELB로그가 elasticbeanstalk-<region>-<account-id> 인 버킷에 에 쌓이는지 확인
(경로: sachiel/AWSLogs/*)
> DEV-10282 Add elb logging settings

- _provisioning/provisioning.py
- run_common.py
- run_create_vpc.py
- 문제가 발생한 AWSCLIv2를 부분 업데이트 합니다.
- 업데이트 대상은 qa_*, johanna 입니다.
- 나머지는 qa_* 및 johanna 에 문제가 해결되면 업데이트 하도록 하겠습니다.
- qa_* codebuild 작업들이 실패없이 진행됨
> DEV-10646 Upgrade to AWSCLIv2 (부분 업데이트)

- run_create_cloudwatch_dashboard.py
- run_create_eb_django_al2.py
- QA Merge: [HotFix] DEV-10870 sync router.py with sachiel
> QA Merge: [HotFix] DEV-10870 sync router.py with sachiel

- run_create_eb_django.py
- run_create_eb_django_al2.py
- QA Merge: [HotFix] 2020 W52 / 2021 W1 버그패치
> QA Merge: [HotFix] 2020 W52 / 2021 W1 버그패치

- run_create_cloudwatch_dashboard.py
- run_create_eb_django.py
- run_create_eb_django_al2.py
- OP Merge: [HotFix] 2020 W52 / 2021 W1 버그패치
> OP Merge: [HotFix] 2020 W52 / 2021 W1 버그패치

- run_terminate_iam.py
> DEV-11177 iam terminate add terminte ssm policy ignore_error

- run_create_eb_windows.py
- QA Merge: W4/5/6/7 Update EB platform version
> QA Merge: W4/5/6/7 Update EB platform version

- run_create_s3_bucket.py
- QA Merge: Fix broken bucket setup
> QA Merge: Fix broken bucket setup

- run_create_eb_windows.py
- run_create_s3_bucket.py
- OP Merge: Fix broken bucket setup
> OP Merge: Fix broken bucket setup

- run_create_eb_django.py
- QA Merge: [HotFix] Increase sachiel: t3.nano -> t3.small
> QA Merge: [HotFix] Increase sachiel: t3.nano -> t3.small

- run_create_eb_django.py
- run_create_s3_bucket.py
- OP Merge: [HotFix] Increase sachiel: t3.nano -> t3.small
> OP Merge: [HotFix] Increase sachiel: t3.nano -> t3.small

- _provisioning/requirements_rpm.txt
- 에러 수정
. provisioning 중 python-devel 설치 중 아래와 같은 에러 발생
. python-devel 버전 수정
- provisioning 시 에러 없이 정상 동작 확인
> DEV-11317 provisioning중 python-devel 설치 버전 수정

- _provisioning/requirements_rpm.txt
- requirements.txt
- 패키지 버전 업데이트
- 프로비저닝이 성공적으로 이루어져야 합니다.
- 기능이 모두 정상적으로 작동해야 합니다.
> DEV-11314 패키지 버전 업데이트

- run_create_eb_windows.py
- daily cd가 일어나면서 인스턴스 수 가 급격하게 줄어들어 필요한 시나리오 잡을 소비하지 못해 전체적 성능 저하
- AWS iam, vpc, eb gendo를 띄워주세요.
- 생성이 완료가 되었다면 AWS console EC2에 들어가 오토스케일 탭으로 들어가주세요.
- gendo의 오토스케일 조정하는 탭으로 들어가 max 사이즈를 1보다 크게 변경해 주세요. 이 후 desired capacity를 2이상으로 변경 해주세요.
- johanna에서 ./run_create_eb.py gendo를 실행해 주세요.
- 새로 생성 된 gendo의 desired capacity가 구 gendo의 desired capacity의 값과 같은지 확인해주세요.
- https://hbsmith.atlassian.net/wiki/spaces/GEN/pages/916422780/TF%2B-%2Bgendo%2B0#gendo-%EA%B0%AF%EC%88%98%EC%97%90-%EC%A1%B0%EC%A0%88%EC%97%90-%EC%98%81%ED%96%A5%EC%9D%84-%EC%A3%BC%EA%B3%A0-%EC%9E%88%EB%8A%94-%EC%9A%94%EC%86%8C 문서의 사진을 참고하면 됩니다.
> DEV-10618 Daily CD시 Instance 수 조절 방안

- run_create_eb_django.py
- run_create_eb_django_al2.py
- run_create_eb_windows.py
- run_create_s3_bucket.py
> QA Merge: W8/9 1st

- run_create_eb_django.py
- run_create_eb_django_al2.py
- QA Merge: W8/9 Update eb version
> QA Merge: W8/9 Update eb version

- run_create_eb_django_al2.py
- QA Merge: Recover read-replica support
> QA Merge: Recover read-replica support

- run_create_eb_django_al2.py
- OP Merge: Recover read-replica support
> OP Merge: Recover read-replica support

- conf.py
- run_common.py
- run_create_eb_django.py
- run_create_eb_django_al2.py
- run_create_eb_windows.py
- run_create_vpc.py
- run_describe_eb.py
- run_terminate_vpc.py
> QA Merge: W10/11 2nd

- README.md
- run_create_codebuild_cron.py
- run_create_codebuild_default.py
- run_create_codebuild_github.py
- run_create_codebuild_vpc.py
- run_create_eb_windows.py
> QA Merge: W14/15 2nd

- run_create_codebuild_common.py
- run_create_codebuild_cron.py
- run_create_codebuild_default.py
- run_create_codebuild_github.py
- run_create_codebuild_vpc.py
- run_terminate_codebuild.py
- run_terminate_codebuild_common.py
- AWS Chatbot + Codebuild 연동 프로비저닝을 추가 했습니다.
- 본인 계정에 AWS Chatbot 을 slack 계정 및 본인 채널과 연동되도록 수동 생성해야 합니다.
- run_create_codebuild.py 하여 codebuild 프로젝트가 notifiaction rule, sns topic, subscription 과 함께 잘 생성됨을 확인합니다.
- codebuild project를 실행했을때 아래 스샷과 비슷한 알람이 뜨는지 확인합니다.
- run_terminate_codebuild.py 하여 프로젝트를 제거하면 notification rule이 함께 제거가 되는지 확인합니다.
> DEV-11641 AWSChatbot + Codebuild 기능추가

- run_create_cloudwatch_dashboard.py
> QA Merge: [HotFix] 1st

- README.md
- OJT 중 빠진 `README.md` 업데이트
- README.md 업데이트로 머지 후에 업데이트된 문서를 확인할 수 있어야 합니다.
> DEV-11664 `README.md` 업데이트

- run_create_cloudwatch_dashboard.py
- run_create_rds.py
- run_create_s3_bucket.py
> QA Merge: W18/19

- run_create_rds.py
> QA Merge: W18/19 2nd

- run_create_eb_django.py
- run_create_eb_django_al2.py
- run_create_eb_windows.py
> QA Merge: W18/19 3rd

- aws_iam/aws-lambda-default-policy.json
- QA Merge: [HotFix] Fix permission error
> QA Merge: [HotFix] Fix permission error

- _provisioning/provisioning.py
- node 버전을 최신 LTS로 갱신
- vagrant로 프로비저닝 후 에러 유무 확인
- https://github.com/HardBoiledSmith/johanna/commit/93dd44429ee1b037afdce2f505d3300e3ab0cdb1
> DEV-11871: node LTS 버전 갱신 (johanna)

- run_create_eb_django_al2.py
- `./run_create_eb_django_al2.py` 상의 오타를 수정합니다.
- sachiel, nerv가 정상적으로 프로비저닝되어야 합니다.
> DEV-11659 `./run_create_eb_django_al2.py` 버그 수정

- _provisioning/provisioning.py
- _provisioning/requirements_rpm.txt
- 문제의 부분 두 군대 수정
- python-devel 버전, pip 링크 생성 부분 수정.
> DEV-12085 vagrant provisioning 시 발생하는 에러 수정

- run_create_eb_django_al2.py
- eb platform을 구버전 -> 신버전으로 업데이트 진행.
> DEV-12025 eb django al2 flatform version update

- _provisioning/provisioning.py
- manifest/aws-windows-deployment-manifest.json
- run_create_eb_windows.py
- DEV-12196 [HotFix] Fix download from us-east-1 to ap-northeast-2
> DEV-12196 [HotFix] Fix download from us-east-1 to ap-northeast-2 

- aws_iam/aws-elasticbeanstalk-ec2-policy.json
- Gendo aws credentials 제거를 위한 `aws-elasticbeanstalk-ec2-policy.json` 수정
- 관련 PR : https://github.com/HardBoiledSmith/gendo/pull/586
- IAM provisioning 이 잘 되어야 합니다.
> DEV-11834 Gendo aws credentials 제거를 위한 `aws-elasticbeanstalk-ec2-policy.json` 수정

- run_create_eb_django.py
> DEV-12172 al2 platform update

- _provisioning/provisioning.py
> QA Merge: W22/23 2nd

- aws_iam/aws-ec2-vpc-endpoint-policy-for-s3.json
- run_create_vpc.py
- run_terminate_vpc.py
- S3 접근 비용절감을 위한 https://hbsmith.atlassian.net/browse/DEV-12189 작업추가
- VPC endpoint 생성 및 삭제 지원
- create_vpc 후 vpc endpoint 에 gateway 타입 1개가 생성되어 있음을 확인
- terminate_vpc 후 vpc endpoint 에 모든 endpoint가 삭제되었음을 확인
> DEV-12189 VPC gateway endpoint 추가

- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- _provisioning/requirements_rpm.txt
- run_common.py
> QA Merge: W32/33/34 1st

- run_create_eb_django.py
> QA Merge: W32/33/34 2nd

- run_common.py
- QA Merge: DEV-12690 delete hack
> QA Merge: DEV-12690 delete hack

- run_common.py
- run_create_cloudwatch_dashboard.py
- OP Merge: DEV-12690 delete hack
> OP Merge: DEV-12690 delete hack

- run_create_imagebuilder_gendo.py
> DEV-12758 imagebuilder_gendo ami version windows 2.6.8 -> 2.7.0

- run_create_eb.py
- run_create_eb_windows2.py
- eb windows(gendo) 의 생성 스크립트를 구 버전에서 image를 사용하는 2 버전으로 우회
- johanna를 통해 gendo환경을 구성해주세요. 스크립트 실행 시 정상적으로 돌아가야 합니다.
> DEV-12938 Gendo image로 생성 되도록 johanna 코드 수정

- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- _provisioning/requirements_rpm.txt
- run_common.py
- run_create_cloudwatch_dashboard.py
- run_create_eb_django.py
> QA Merge : W38/39/40 1st 

- _provisioning/provisioning.py
- node.js 버전을 최신으로 업그레이드 하고 node, npm 버전이 노출될수 있도록 수정 (문제발생시 추적용)
- npm 버전은 해당 node 버전의 기본버전을 사용하도록 수정
> DEV-12890 Update node.js version

- .github/dependabot.yml
> QA Merge: W44/45/46 2nd

- run_create_eb_django.py
- run_create_eb_windows.py
- eb platform 버전을 업데이트 
- sachiel, nerv: 3.3.6 -> 3.3.7
- gendo: 2.7.1 -> 2.7.2
> DEV-13336 Update EB platform

- .github/dependabot.yml
> QA Merge: W44/45/46 3st 

- run_create_s3_vue.py
- 2.0 UI 프로젝트 OP 자동배포에 포함
- 패치후 아래 주소로 접속 가능한지 확인
- DV/QA https://<prefix>-app2.hbsmith.io
- OP https://app2.hbsmith.io
> DEV-13273 2.0 UI 프로젝트 OP 자동배포에 포함

- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
- eb verison update 2.7.2 -> 2.8.0
> DEV-13519 windows flatform version update

- run_create_s3_vue.py
> QA Merge: W47/48/49 2nd

- run_create_eb_windows.py
> QA Merge: W47/48/49 3rd

- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_ses_sqs.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
- lambda function 업데이트가 늦어져서 이후의 설정 업데이트 시도가 실패하는 문제 해결
> QA Merge: DEV-13520

- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_ses_sqs.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
- AWS Compute optimizer 권고로 connect_recovery 람다함수 메모리를 128MB->160MB로 증설필요
- 본 PR과 하기 magi PR로 kaji 람다함수들 정상 프로비저닝 되는지 확인
- https://github.com/HardBoiledSmith/magi/pull/843
- connect_recovery 람다만 160MB 로 증설이 가능한지 여부 확인
> DEV-13637 conect_recovery 람다함수 메모리 증설

- run_create_imagebuilder_gendo.py
- gendo imagebuilder eb platform update
> DEV-13832 패치 지원 johanna: gendo imagebuilder eb platform update

- README.md
- Fake Email 테스트 환경세팅 Readme.md 추가
> DEV-13717 Fake Email 테스트 환경세팅 Readme.md 추가

- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
- Gendo Image version update
- 2.8.2 -> 2.8.3
> DEV-14227 Gendo Image EB version update

- README.md
> QA Merge: W10/11/12 1st

- run_create_eb_django.py
- run_create_eb_windows.py
> QA Merge: W10/11/12 2nd

- run_create_imagebuilder_gendo.py
> QA Merge: W10/11/12 3rd

- run_create_eb_django.py
- DEV-14597 eb linux platform version update 3.3.11 -> 3.3.12
> DEV-14597 eb linux platform version update 3.3.11 -> 3.3.12

- run_create_eb_django.py
- run_create_imagebuilder_gendo.py
- QA Merge: W13/14/15 2nd
- eb linux platform version update
> QA Merge: W13/14/15 2nd

- _provisioning/provisioning.py
- node, 14.19.1, npm 6.14.16 버전 업데이트
- vagrant up 동작확인
> DEV-14739 전체 저장소에서 node 및 npm 버전 업데이트

- run_create_imagebuilder_gendo.py
- run_create_imagebuilder_gendo platform version update 2.9.0 -> 2.9.1
> DEV-14786 run_create_imagebuilder_gendo platform version update 2.9.0 -> 2.9.1

- run_create_eb_windows.py
- QA Merge: DEV-14787 upgrade gendo to t3.large
> QA Merge: DEV-14787 upgrade gendo to t3.large

- run_create_eb_windows.py
> QA Merge: W19/20/21 1st 

- run_create_eb_windows.py
> OP Merge: W19/20/21 1st

- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
> DEV-15302 eb windows platform version update 2.9.1 -> 2.10.0

- _provisioning/provisioning.py
- run_create_codebuild_common.py
- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
> QA Merge: W22/23/24 1st

- run_create_codebuild_common.py
- https://github.com/HardBoiledSmith/johanna/pull/598 반영
> QA Merge: W22/23/24 2nd

- run_create_eb_windows.py
- https://github.com/HardBoiledSmith/johanna/pull/598 적용
> OP Merge: W23/24/25 2nd

- run_create_eb_django.py
- run_create_eb_windows.py
> QA Merge: W26/27/28 1st

- run_create_imagebuilder_gendo.py
- DEV-15392 gendo image version update
> DEV-15392 gendo image version update

- run_create_eb_django.py
- run_create_eb_windows.py
>  QA Merge: W26/27/28 2nd

- run_create_codebuild_common.py
- run_create_eb_django.py
- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
> OP Merge: W25/26/27 1st

- run_create_eb_django.py
- run_create_eb_windows.py
> QA Merge: W28/29/30 1st

- run_create_eb_windows.py
> OP Merge: W28/29/30 1st 

- run_create_eb_windows.py
- run_create_imagebuilder_gendo.py
- [gendo] 이미지 생성 실패
- 최신 버전이 업데이트 되어 이미지 생성 스크립트가 실패 됨.
> DEV-15888 gendo eb platform version update

- run_create_eb_django.py
> QA Merge: W31/32/33 2nd

- run_common.py
- [QA패치 버그 수정] run_create_eb.py version 참조에 필요한 문자 빠진 버그 수정
> DEV-16152 [QA패치 버그 수정] run_create_eb.py version 참조에 필요한 문자 빠진 버그 수정

- run_create_eb_django.py
> QA Merge: W34/35/36 2nd

- run_create_codedeploy_ramiel.py
> QA Merge: W37/38/39 2nd

- run_create_codedeploy_ramiel.py
- 인스턴스 태깅은 10개 단위로 나누어서 진행
- QA/OP 패치에서 정상 동작 확인
> DEV-16367 [라미엘] 온프레미스 인스턴스 태깅 한도 10 제한, qa 배포 인스턴스 한정

- run_create_codedeploy_ramiel.py
> QA Merge: W37/38/39 3rd

- run_create_s3_bucket.py
- app console(브라우저)에서 블랙리스트 사진을 업로드 하기 위한 CORS 추가 
- 해당 브랜치의 vagrant johanna를 띄워주세요.
- ssh 접속 후 ./run_create_s3.py {개발자명}-dv-hbsmith-temp 를 입력해주세요.
- s3 temp-bucket에 cors설정이 아래 사진과 같이 되어야 합니다.
dv
qa
op
> DEV-16546 [johanna] temp 버킷에 COS 설정 추가하는 기능 추가

- run_create_eb_django.py
- DEV-16571 [QA 패치] eb al2 version update
> DEV-16571 [QA 패치] eb al2 version update

- run_terminate_imagebuilder_gendo_old_environment.py
- DEV-16587 run_terminate_imagebuilder_gendo_old_environment.py logic fix
- 삭제 대상 조건문 로직 수정.
- 사용중인 버전 조회에 대해 로그에 찍히도록 변경.
> DEV-16587 run_terminate_imagebuilder_gendo_old_environment.py logic fix

- run_common.py
- EB django 버전 업데이트에 따른 진행.
- eb gendo가 정상적으로 프로비저닝 되어야 합니다.
> DEV-16753 EB gendo 버전 업데이트

- run_create_eb_django.py
> QA Merge: W43/44/45 2nd

- run_common.py
- DEV-16893 gendo eb version update
> DEV-16893 gendo eb version update

- run_create_eb_django.py
> QA Merge: W49/50/51/52 2nd

- run_create_codebuild_common.py
- run_create_codebuild_vpc.py
- QA Merge: [HotFix] DEV-17298
[DEV-17298]: https://hbsmith.atlassian.net/browse/DEV-17298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> QA Merge: [HotFix] DEV-17298

- run_common.py
- run_create_eb_django.py
- EB django, windows 플랫폼 버전 업데이트
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
- AWS 환경 구성 시 EB 인스턴스가 정상적으로 생성 되어야 합니다.
> DEV-17437 EB Platform version update

- run_common.py
- run_create_codebuild_common.py
- run_create_eb_django.py
> QA Merge : W1/2/3/4 1st

- run_common.py
- run_create_eb_django.py
- run_create_eb_windows.py
- 이 PR이 해결하고자 하는 이슈(JIRA Issue) 및 작업 내용에 대해 설명해 주세요
- 이 PR을 테스트 하는 방법에 대해 간략히 설명해 주세요
- 이 PR의 리뷰에 참고가 되는 스크린샷을 첨부해 주세요 (필요하다면)
> QA Merge: [HotFix] DEV-17638

- run_create_codebuild_common.py
- DEV-17638 [gendo] HotFix: 스케일링 정책 수정
> OP Merge: [HotFix] DEV-17638

- run_create_eb_django.py
> QA Merge: W5/6/7 2nd

- run_create_eb_django.py
- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_ses_sqs.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
- run_create_s3_vue.py
- eb_django, lambda 컴퓨팅 아키텍처를 arm64로 교체
- `BRANCH=DEV-17682 vagrant up`
- johanna ssh 접속
- aws에 환경 구축
```bash
./run.py create_vpc -f
./run.py create_rds -f
./run.py create_eb -f
./run.py create_sns -f
./run.py create_sqs -f
./run.py create_lambda -f
./run.py create_s3 -f
./run_create_ec2_client_vpn.py -f
./run_create_acm_certificate.py -f
```
- VPN 접속 후 데이터베이스 초기화
- 서비스 정상 확인
- nerv 모든 대시보드 정상 확인
- 앱콘솔 접속 후 모든 대시보드 정상 확인
- 앱콘솔 접속 후 임의의 job 녹화 후 업로드하고 정상 수행 확인
- arm64 적용 확인
- AWS 콘솔 --> ec2 --> t4g.small 인스턴스 확인
- AWS 콘솔 --> lambda --> 아키텍처 --> arm64 확인
- 톱니 --> architecture 활성화 필요
> DEV-17682 [AWS FTR] sachiel, nerv, lambda 에서 graviton 교체 가능한지 확인

- run_create_eb_windows.py
- run_create_sqs.py
- run_terminate_sqs.py
- SQS Type에 따른 생성 코드 분리.
- SQS 변수 변경에 따른 gendo 관련 코드 병행 수정.
**연관PR**
https://github.com/HardBoiledSmith/kaji/pull/1391
https://github.com/HardBoiledSmith/gendo/pull/1241
https://github.com/HardBoiledSmith/magi/pull/1035
사전 준비 : 해당 브랜치의 johanna, magi 압축해제 후 config 값 johanna의 config.json에 복사
아래 스탭대로 johanna를 통해 AWS환경을구성해주세요.
1. ./run_create_vpc
2. ./run_create_rds
3. ./run_create_ec2_client_vpn
4. vpn 연결 후 reset database 진행
5. ./run_create_sqs
6. ./run_create_eb sachiel
7. ./run_create_eb -b DEV-17798 gendo
8. ./run_create_sns
9. ./run_create_lambda -b DEV-17798
10. ./run_create_s3
12. ./run_create_cloudwatch_dashboard -b DEV-17798
job 전체 실행 후 순차 실행 되는 지 확인.
... 11번까지 순차 실행 되는 부분 확인 완료.
Cloudwatch DASHBOARD에 정상적으로 정보 노출 여부 확인.
SQS 정상적으로 자원 생성되었는지 확인.
cloudwatch alarm 경보 정상 적용
> DEV-17798 visual_test_result SQS standard -> fifo타입으로 전환

- run_common.py
- DEV-17764 [QA패치] window platform 버전 업데이트
> DEV-17764 [QA패치] window platform 버전 업데이트

- run_create_cloudwatch_alarm.py
- QA Merge: [hot-fix] DEV-17837 [gendo] 매직넘버 수정: 15~50대로 운영
> QA Merge: [hot-fix] DEV-17837 [gendo] 매직넘버 수정: 15~50대로 운영 

- run_create_eb_django.py
- QA Merge: W11/12/13 update platform
> QA Merge: W11/12/13 update platform

- run_create_eb_django.py
- run_create_eb_windows.py
> OP Merge: W11/12/13 1st

- buildspec.yml
> QA Merge: W11/12/13 2nd

- buildspec.yml
- run_create_eb_django.py
> OP Merge: W11/12/13 2nd

- _provisioning/Vagrantfile
- vagrant 배포 오류 수정
- 참조
- https://github.com/HardBoiledSmith/sachiel/pull/1317
- https://github.com/HardBoiledSmith/hbsmith-database/pull/420
- https://github.com/HardBoiledSmith/nerv/pull/632
- https://github.com/HardBoiledSmith/hbsmith-web/pull/1680
- https://github.com/HardBoiledSmith/kaji/pull/1406
- https://github.com/HardBoiledSmith/johanna/pull/691
- vagrant up 성공
> DEV-18128 fedora 35 EOL에 의한 저장소 아카이브 처리 대응

- run_create_codebuild_cron.py
- run_create_codebuild_default.py
- run_create_codebuild_vpc.py
- 누락된 container_type 추가
- 참조
- https://github.com/HardBoiledSmith/magi/pull/1070
- https://github.com/HardBoiledSmith/sachiel/pull/1324
- https://github.com/HardBoiledSmith/hbsmith-web/pull/1691
- https://github.com/HardBoiledSmith/johanna/pull/694
- QA/OP에서 reset_database codebuild 성공
> DEV-17875 [AWS FTR] 아키텍처 교체: codebuild

- run_common.py
- run_create_eb_django.py
- DEV-18137 EB Platform version update
EB 생성 및 이미지 생성이 정상적으로 되어야 합니다.
참조 : https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.net
> DEV-18137 EB Platform version update

- run_create_athena.py
#!/usr/bin/env python3 코드 라인이 빠져있어 아래 에러 발생
> DEV-18047 run_create_athena 빠진 코드 추가

- _provisioning/Vagrantfile
- _provisioning/provisioning.py
- al2 프로비저닝 코드 삭제
- vagrant up 성공
- ssh로 dv-johanna.hbsmith.io 접속 성공
- 참조
- https://github.com/HardBoiledSmith/nerv/pull/640
- https://github.com/HardBoiledSmith/hbsmith-database/pull/426
- https://github.com/HardBoiledSmith/kaji/pull/1420
- https://github.com/HardBoiledSmith/hbsmith-web/pull/1720
- https://github.com/HardBoiledSmith/johanna/pull/701
- https://github.com/HardBoiledSmith/sachiel/pull/1328
> DEV-18133 naoko,gendo 제외한 모든 arm64 지원 vagrant에서 awslinux2 프로비저닝 코드 삭제 (arm64 fedora 프로비저닝 코드만 남김)

- run_common.py
- DEV-18290 eb window platform version update 2.11.2 -> 2.11.3
- eb platform 버전 업데이트에 따른 반영
출처 : https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.python
- image builder gendo 가 실패없이 돌아야 합니다.
> DEV-18290 eb window platform version update 2.11.2 -> 2.11.3

- run_create_cloudwatch_dashboard.py
> QA Merge: W17/18/19 2nd

- run_create_eb_django.py
> QA Merge: W17/18/19 3rd

- run_create_cloudwatch_dashboard.py
- run_create_eb_django.py
> OP Merge: W17/18/19 3rd

- run_create_cloudwatch_dashboard.py
- run_create_eb_django.py
> QA Merge: W20/21/22 1st 

- run_create_eb_django.py
> QA Merge: W24/25/26 1st

- run_create_codedeploy_ramiel.py
- 다음 오류 수정:
- 단일 인스턴스 OP 패치 성공
- 0017 대상으로 해볼 것
> DEV-18708 [라미엘] 원클릭 배포 ruby 버전 업그레이드

- run_common.py
> QA Merge: W27/28/29 1st

- run.py
- run_common.py
- run_create_cloudwatch_dashboard.py
- run_create_eb_django.py
- run_create_sqs.py
- run_terminate_rds.py
- 주말 35 -> 30 조정 및 eb 플랫폼 버전 업그레이드
> DEV-19016 [magi, johanna] 주말 35 -> 30 조정 및 eb 플랫폼 버전 업그레이드

- run_create_imagebuilder_gendo.py
- ImageBuilder 이미지 생성 후 검증 과정에서 필수 프로그램 설치여부 검증단계 컴포넌트 추가
**관련 PR**
- https://github.com/HardBoiledSmith/gendo/pull/1374
- 해당 브랜치의 johanna를 띄워주세요.
- johanna에 접속 후 ./run_create_imagebuilder_gendo.py -b DEV-18370 를 실행해주세요.
- AWS에 접속하여 imagebuilder 서비스에 접속 후 이미지가 정상적으로 생성 되었는지 확인해주세요.
**이미지 생성 성공**
install log 확인
exception 없음
---
**필수 프로그램이 없어 검증 단계에서 실패**
실패 로그 기록.
> DEV-18370 [gendo] ImageBuilder 이미지 생성후 검증 과정에서 필수 프로그램 설치여부 검증 추가

- run_common.py
- eb gendo platform version update
- johanna에서 AWS gendo provisioning이 정상적으로 생성되어야 합니다.
> DEV-19198 eb gendo platform version update

- run_create_route53_health_check.py
- 소프트캠프용 미니PC noVNC 엔드포인트에 Route53 - SNS - PagerDuty 연결
- 해당 endpoint는 https가 아닌 Http로 접속을 해야하여 생성 스크립트를 수정했습니다.
**연관 PR**
https://github.com/HardBoiledSmith/magi/pull/1119
- 해당 브랜치의 johanna와 magi의 config 값 세팅
- ./run_create_sns.py soft-camp-status-notification
- ./run_create_route53_health_check.py soft-camp
자원 생성을 진행해주세요.
- AWS sns, route53 helath check, cw 서비스와 pagerguey에 접속하여 해당 값이 있는지 확인 되어야 합니다.
**route53 helath check**
**CW**
**SNS**
**Pagerduty**
> DEV-19350 소프트캠프용 미니PC noVNC 엔드포인트에 Route53 - SNS - PagerDuty 연결

- run_common.py
- run_create_eb_django.py
- DEV-19493 AWS EB platform update ( linux, windows server)
> DEV-19493 AWS EB platform update ( linux, windows server)

- run_common.py
- run_create_eb_django.py
- run_create_route53_health_check.py
> QA Merge: W39/40/41/42 2nd

- run_create_cloudwatch_dashboard.py
- EB cloudwatch dashboard code fix ( new version = 'awseb--' , old version = 'awseb-') 
- 자동생성 시 지어지는 네이밍 규칙이 변경이 되어있음
> DEV-19508 OP환경 Codebuild EB 실패 원인 파악 및 해결 

- run_create_eb_windows.py
- 주중&주말 오후 7시부터 6대로 감축
- 주말 낮 27대 유지
- 주중 낮 45대 유지
- 배포후 변경된 스케쥴대로 운영되는지 확인
> DEV-19619 Gendo Magic Number 조정

- aws_iam/aws-s3-bucket-policy-for-ramiel-op-bundle.json
- run_create_s3_bucket.py
- op계정에 라미엘 자산 생성
- 참조
- https://github.com/HardBoiledSmith/magi/pull/1131
- https://github.com/HardBoiledSmith/johanna/pull/744
- op 계정에서 op-hbsmith-ramiel 정상 유지 확인
> DEV-17859 [라미엘] op-hbsmith-ramiel 버킷 등 수동 생성 자산들 자동화

- run_create_eb_django.py
> QA Merge: W46/47/48 1st

- run_create_s3_bucket.py
- op 계정에서만 op-hbsmith-ramiel  버킷 생성
- qa/op s3배포 이슈 해결
> DEV-19814 magi op-ramiel 에러 발생 원인 파악 및 해결

- aws_iam/aws-s3-bucket-policy-for-ramiel-op-bundle.json
- run_create_s3_bucket.py
> QA Merge: W46/47/48 2nd

- run_create_s3_bucket.py
> DEV-19806 [시스템 전체] 결과 보관기간 2개월 -> 12개월 일괄 연장

- run_create_s3_bucket.py
> QA Mege: DEV-19806 

- run_create_cloudwatch_dashboard.py
> OP Merge: W46/47/48 1st

- run_create_s3_bucket.py
> QA Merge: DEV-19853

- run_create_s3_bucket.py
> OP Merge: DEV-19853

- run_create_s3_bucket.py
> QA Merge: W49/50/51 1st

- run_common.py
- run_create_eb_django.py
> QA Merge: W49/50/51 2nd

- run_create_eb_django.py
> QA Merge: W49/50/51 3rd

- run_common.py
- run_create_eb_django.py
> OP Merge: W49/50/51 2nd

- run_common.py
- DEV-20109 EB windows platform version update
> DEV-20109 EB windows platform version update

- run_create_eb_django.py
- QA Merge: Dev 2023 W52 2024 W1/2/3
> QA Merge: Dev 2023 W52 2024 W1/2/3

- run_common.py
- run_create_eb_django.py
- OP Merge: Dev 2023 W52 2024 W1/2/3
> OP Merge: 2023 W52 2024 W1/2/3 1st

- _provisioning/provisioning.py
- run_common.py
- run_create_eb_django.py
> QA Merge: 2024 W4/5/6 1st

- run_create_s3_bucket.py
> QA Merge: DEV-20291 fix

- run_create_s3_bucket.py
> QA Merge: 2024 W4/5/6 3rd

- _provisioning/provisioning.py
- run_common.py
- run_create_eb_django.py
- run_create_s3_bucket.py
> OP Merge: 2024 W4/5/6 1st

- run_create_eb_windows.py
- 무한 실행되는 인스턴스가 현재 실행중인 EB 환경인지, 이미 종료된 환경인지 파악이 안되어 해당 로그를 남기기로 함
> DEV-20342 [gendo] OP 패치이후 일부 Deep QA에서 업로드가 실패하거나 무한 실행되는 이슈 발생

- run_create_s3_bucket.py
> QA Merge: 2024 W4/5/6 4th

- run_create_eb_windows.py
- run_create_s3_bucket.py
> OP Merge: 2024 W4/5/6 2nd

- run_create_s3_bucket.py
> QA Merge: 2024 W7/8/9 1th

- _provisioning/requirements.txt
- run_create_eb_windows.py
- run_create_s3_bucket.py
> OP Merge: 2024 W7/8/9 1th 

- run_common.py
- run_create_eb_django.py
- DEV-20497 eb platform version update
> DEV-20497 eb platform version update

- run_common.py
- run_create_eb_django.py
- run_create_eb_windows.py
> QA Merge: W13/14/15 1st 

- run_create_lambda_iam.py
- [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패 원인 파악을 위한 코드 추가
> DEV-20875 [QA패치] [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패

- run_create_lambda_iam.py
- QA Merge: W16/17/18 3rd
- 디버깅을 위한 코드 추가.
> QA Merge: W16/17/18 3rd

- run_create_lambda.py
- DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패
> DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패

- run_create_lambda_iam.py
- QA Merge: DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패
> QA Merge: DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패

- run_common.py
- run_create_lambda.py
- run_create_lambda_iam.py
- DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패
> DEV-20940 [QA] code build qa_craete 진행 시 lambda 생성 단계에서 실패 

- run_common.py
- run_create_eb_django.py
- QA Merge: Dev 2024 W19/20/21 1st
> QA Merge: Dev 2024 W19/20/21 1st

- run_create_eb_windows.py
- 운영팀 요청으로 주중 오전 5시 ~ 오전 7시:  10대 증설 스케쥴 추가
- 연관이슈: https://github.com/HardBoiledSmith/magi/pull/1205
- 정상적으로 환경 생성됨
> DEV-21222 [데이터팀 : 개발팀] 5/24 갠도 수 조정 요청

- run_common.py
- run_create_eb_django.py
- QA Merge: [HotFix] DEV-21222
> QA Merge: [HotFix] DEV-21222

- run_common.py
- run_create_lambda_cron.py
- elastic beanstalk, imagebuilder window image version update
- windows 이미지를 사용하는 imagebuilder 및 EB 생성 시 문제없이 되어야 합니다.
https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platforms-supported.html#platforms-supported.net
> DEV-21236 elastic beanstalk, imagebuilder window image version update

- run_create_vpc.py
- network acl로 ssh, rdp 포트 차단
- DEV-21087로 johanna 배포
- ./run_create_vpc -f;
- ACL 확인
- eb, rds vpc의 default security groups --> rule이 없어야 함
> DEV-21087 [johanna] VPC 네트워크 보안 강화

- run_create_eb.py
- run_create_eb_iam.py
- run_create_eb_ramiel_coturn.py
- run_create_vpc.py
- TURN 서버 EB화
- EB 설정 추가
- ramiel에 turn 서버 설정 추가
- 참조
- https://github.com/HardBoiledSmith/magi/compare/DEV-20873?expand=1
- https://github.com/HardBoiledSmith/johanna/pull/803
- https://github.com/HardBoiledSmith/ramiel/pull/548
- OP에서 배포 성공
- AWS op 계정의 route53 계정의 op-ramiel-coturn-1.hbsmith.io, op-ramiel-coturn-1.hbsmith.io DNS A 레코드 갱신됨
> DEV-20873 [라미엘] TURN서버 EB화 #2

- run_terminate_vpc.py
- DEV-21148 [QA] 생성 시 추가된 vpc acl 코드 terminate 스크립트에 내용 추가
> DEV-21148 [QA] 생성 시 추가된 vpc acl 코드 terminate 스크립트에 내용 추가

- run_create_eb_windows.py
- 6/13 gendo c7i.large -> r7i.large로 전환
> 6/13 gendo c7i.large -> r7i.large로 전환

- run_create_eb_windows.py
- [johanna] 모든 EB 환경에 대해서 가용성 확인 코드 적용 및 핫픽스
정상 생성 확인 완료
> [johanna] 모든 EB 환경에 대해서 가용성 확인 코드 적용 및 핫픽스

- run_create_eb_windows.py
- QA Merge: [johanna] 모든 EB 환경에 대해서 가용성 확인 코드 적용 및 핫픽스
> QA Merge: [johanna] 모든 EB 환경에 대해서 가용성 확인 코드 적용 및 핫픽스

- run_create_eb_windows.py
- gendo 수 조정
- 주중 4개 주말 2개 스케쥴
- crontab 시간을 한국시간으로 조정
- https://github.com/HardBoiledSmith/magi/pull/1219
- 정상적으로 세팅
> DEV-21260 [HotFix][데이터팀:개발팀] [6/14] gendo수 조정 안

- run_create_eb_windows.py
- run_terminate_vpc.py
> QA Merge: W22/23/24 3rd

- run_create_eb_windows.py
- QA Merge: [HotFix] DEV-21260
> QA Merge: [HotFix] DEV-21260

- run_create_eb_windows.py
- run_terminate_vpc.py
- OP Merge: [HotFix] DEV-21260
> OP Merge: [HotFix] DEV-21260

- run_create_eb_windows.py
- 메모리 수집 추가
- 참조
- https://github.com/HardBoiledSmith/gendo/pull/1726
- https://github.com/HardBoiledSmith/johanna/pull/821
- https://github.com/HardBoiledSmith/magi/pull/1222
- gendo AWS 배포: `./run_create_eb.py -b DEV-21240 gendo -f`
- gendo cw dashboard 배포: `./run_create_cloudwatch_dashboard.py -b DEV-21240 gendo -f`
- AWS 대시보드에서 cw dashboard --> gendo 참조
- 사용량 %: Memory % Comitted byte in use
- 페이지 사용량 %: Paging File % Usage
> DEV-21240 [gendo] EB에 메모리 모니터링 cloudwatch 설정 추가 & cloudwatch 대시보드 위젯 추가

- run_create_eb_windows.py
- QA Merge: [HotFix] DEV-21240
> QA Merge: [HotFix] DEV-21240

- run_create_eb_windows.py
- run_terminate_vpc.py
- OP Merge: [HotFix] DEV-21240
> OP Merge: [HotFix] DEV-21240

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- QA Merge: 2024 W25/26/27 1st
> QA Merge: 2024 W25/26/27 1st

- run_common.py
- QA Merge: 2024 W25/26/27 2nd
> QA Merge: 2024 W25/26/27 2nd

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- QA Merge: 2024 W25/26/27 3rd
> QA Merge: 2024 W25/26/27 3rd

- run_create_eb_windows.py
- QA Merge: [HotFix] DEV-21481 scale down gendo
> QA Merge: [HotFix] DEV-21481 scale down gendo

- run_create_eb_windows.py
- DEV-21549 [QA] gendo 환경 교체 시 종료 로직 exception발생
- gendo측에서 desired capacity를 줄이면서 종료를 하려 했으나, Min size에 의해 종료가 불가해져 발생한 exception
> DEV-21549 [QA] gendo 환경 교체 시 종료 로직 exception발생

- run_create_eb_windows.py
- run_terminate_eb_old_environment.py
> QA Merge: W28/29/30 2nd 

- run_create_eb_windows.py
- DEV-21551 [Gendo] 환경 조회 API Rate Limit 방안책 강구
> DEV-21551 [Gendo] 환경 조회 API Rate Limit 방안책 강구

- run_create_eb_windows.py
> QA Merge: W28/29/30 3rd

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
> DEV-21678 2024-7-31 eb 솔루션 스택 업데이트 (3.7.1)

- run_create_lambda_cron.py
- run_create_lambda_default.py
- run_create_lambda_event.py
- run_create_lambda_ses_sqs.py
- run_create_lambda_sns.py
- run_create_lambda_sqs.py
- AL2023 + python3.12 이미지 사용
- 참조
- https://github.com/HardBoiledSmith/johanna/pull/840
- https://github.com/HardBoiledSmith/magi/pull/1238
- 개발환경/QA/OP 풀 배포
- 빨강/노랑/녹색불 테스트 녹화
- dooray제외 모든 알람수단 체크
- 상기 3개 테스트 수행
- 대시보드 --> __global__ap-northeast-2 --> [Lambda] Errors (all regions) --> 에러 없음 확인
- 상기 connect call의 경우 amazon connect instance가 없어 발생하는 문제임
> DEV-21433 AWS 환경 업그레이드: AL2023 + python 11 - lambda

- run_create_eb_django.py
- kaji dashboard 및 알람 구성
**연관 PR**
https://github.com/HardBoiledSmith/magi/pull/1237
https://github.com/HardBoiledSmith/kaji/pull/1994
- ./run_create_vpc.py
- ./run_create_eb.py kaji -b DEV-21033
- ./run_create_dashboard.py kaji -b DEV-21033
- ./run_create_cloudwatch_alarm.py kaji -b DEV-21033
환경이 정상 생성 되어야 하고 지표들이 대시보드에 정상 집계 되어야 합니다
> DEV-21033 [kaji] Dashboard 추가

- run_common.py
- run_create_eb_django.py
- DEV-21829 [Johanna] ElasticBeanstalk platform version update
- 정상적으로 AWS환경에 Linux, windows 환경에서 프로비저닝이 되어야 합니다.
> DEV-21829 [Johanna] ElasticBeanstalk platform version update

- run_common.py
- run_create_eb_django.py
- run_create_eb_windows.py
> QA Merge: W33/34/35 1st 

- run_create_eb_windows.py
> QA Merge: W33/34/35 2nd

- run_common.py
- run_create_eb_django.py
-DEV-21991 eb platform 버전 업데이트
> DEV-21991 eb platform 버전 업데이트

- run_create_eb_windows.py
- DEV-22146 run_create_eb_windows.py 배포 스크립트 수정
- boto3 규격 변경으로 인한 것으로 추정됨. split하여 개별로 삭제하도록진행.
> DEV-22146 run_create_eb_windows.py 배포 스크립트 수정

- run_create_imagebuilder_gendo.py
> QA Merge: W40/41/42 2nd

- run_create_eb_windows.py
> QA Merge: W40/41/42 3rd

- run_create_eb_django.py
> QA Merge: W40/41/42 4th

- run_create_eb_ramiel_coturn.py
- 라미엘 coturn server 용 cw 대시보드 추가
- 참조
- https://github.com/HardBoiledSmith/ramiel/pull/634
- https://github.com/HardBoiledSmith/johanna/pull/869
- https://github.com/HardBoiledSmith/magi/pull/1264
- 배포
- johanna 배포: `BRANCH=DEV-21253 vagrant up`
- johanna 접속
- 환경 배포
```bash
./run.py create_vpc -f
./run_create_eb.py ramiel-coturn -f
./run_create_cloudwatch_dashboard.py -b DEV-21253 ramiel-coturn -f;
```
- 확인: AWS 콘솔 --> 개인 개발 계정 --> cloudwatch --> dashboard --> ramiel-coturn-...
> (WIP) DEV-21253 [라미엘2] ramiel-coturn Dashboard & Alarm 구성 검토 및 구현

- run_common.py
- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
> QA Merge: W46/47/48 3rd

- aws_iam/aws-s3-bucket-policy-for-result-bucket.json
- run_create_s3_bucket.py
- DEV-22447 [OP 패치] 패치관련 에러 수정 - op-hbsmith-result Policy
> DEV-22447 [OP 패치] 패치관련 에러 수정 - op-hbsmith-result Policy

- run_common.py
- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
> QA Merge: W46/47/48 4th

- run_create_s3_bucket.py
- 아래 수정으로 인해 website 세팅이 필요한 버킷들이 세팅이 안되어 있는 문제 해결
- https://github.com/HardBoiledSmith/johanna/commit/29a2cd5984cb162505b68181899630bf42d07a6f#diff-3c384b051caf37ee96d8d0c83c6714542e44caa523a1fac78205ecd6a46ea29dL89
> DEV-22592 [QA] johanna result 버킷 webhosting 버그수정

- aws_iam/aws-s3-bucket-policy-for-result-bucket.json
- run_create_s3_bucket.py
- QA Merge: DEV-22592 [QA] johanna result 버킷 webhosting 버그수정
> QA Merge: DEV-22592 [QA] johanna result 버킷 webhosting 버그수정 

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- run_create_eb_windows.py
- QA Merge: 2024 W52 2025 W1/2 2nd
> QA Merge: 2024 W52 2025 W1/2 2nd

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- run_create_eb_windows.py
- QA Merge: 2024 W52 2025 W1/2 3rd
> QA Merge: 2024 W52 2025 W1/2 3rd

- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- run_create_eb_windows.py
- QA Merge: 2024 W52 2025 W1/2 4th
> QA Merge: 2024 W52 2025 W1/2 4th

- run_terminate_cloudwatch_log_group.py
- QA Merge: 2024 W52 2025 W1/2 5th
> QA Merge: 2024 W52 2025 W1/2 5th

- run_create_lambda.py
- run_create_lambda_url.py
- run_terminate_lambda.py
- slack 메세지 필터링 하여 화면으로 조회해 볼수있는 기능 추가위해 lambda function url 생성하는 코드 작성
- 연관이슈
- https://github.com/HardBoiledSmith/sachiel/pull/1742 
- lambda function url 생성가능
> DEV-22658 [안건작성] 문자 및 슬랙 포워딩 서버 정식기능 편입 및 편의기능 추가 #3

- run_common.py
- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- QA Merge: 2025 W12/13/14 1st
> QA Merge: 2025 W12/13/14 1st 

- run_common.py
- run_create_eb_django.py
- run_create_eb_ramiel_coturn.py
- OP Merge: 2025 W12/13/14 1st
> OP Merge: 2025 W12/13/14 1st 

- run_common.py
- run_create_eb_django.py
- DEV-23350 eb platform version update
> DEV-23350 eb platform version update

- run_common.py
- run_create_eb_django.py
- run_create_imagebuilder_gendo.py
-  QA Merge: 2025 W30/31/32 1st
>  QA Merge: 2025 W30/31/32 1st 

- run_create_eb_django.py
- DEV-23355 [OP패치] django python version update
> DEV-23355 [OP패치] django python version update

- run_create_eb_django.py
> DEV-23454 eb python version update

- run_create_eb_windows.py
- Gendo 생성 시 autoscaling 시간 변경 내용이 반영되어 있어야 합니다.
> DEV-23531 Gendo 수 조정안 반영 요청 (2025-08-08)

- run_create_eb_django.py
- run_create_eb_windows.py
- QA Merge: 2025 W33/34/35 1st
> QA Merge: 2025 W33/34/35 1st 
